---
title: "Recruitment outcomes of individuals screened for eligibility according to recruitment channels"
author: "Michele Himadi"
date: "2023-06-02"
output: html_document
---
```{r, include=FALSE}
##-------------- 
# **************************************************************************** #
# ***************                Project Overview              *************** #
# **************************************************************************** #
# Author:      Dominick Lemas, Michele Himadi
# Date:        Nov 17, 2020 
# Modify:      June 10, 2024
# IRB:         UFHealth Early Life Exposures and Pediatric Outcomes (IRB201601899) 
# version: R version 4.0.2 (2020-06-22)
# version: Rstudio version Version 1.3.959 
# **************************************************************************** #
# ***************                Description                   *************** #
# **************************************************************************** #
# PLAN: Access redcap via API and pull/format/clean data for downstream analysis.
# Note: vpn must be active
# Next steps
#- function to call the IDs and events
#- function to batch pull EHR data by year/event and combine into final dataset. 
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
# **************************************************************************** #
# ***************                Library                       *************** #
# **************************************************************************** #
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
library(tidyverse)
library(dplyr)
library(flextable)
library(gt)
library(formattable)
library(gtsummary)
library(ggplot2)
library(ggrepel)
library(keyringr)
library(readxl)
library(redcapAPI)
library(REDCapR)
library(vtree)
library(vistime)
library(labelled)
library(plyr)
library(plotly)
library(tidyquant)
library(readr)
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#Recruitment outcomes of individuals screened for eligibility according to recruitment channels
recruitment_outcomes <- Phone_Screen_age_bmi %>% select(Recruitment, Outcomes) %>% na.omit() %>% filter(!str_detect(Recruitment, "Incomplete"))

vtree(recruitment_outcomes, "Recruitment Outcomes", palette=3, sortfill=TRUE, horiz=FALSE)

contingency_table <- table(recruitment_outcomes$Recruitment, recruitment_outcomes$Outcomes)

chi_squared_test <- chisq.test(contingency_table)

chi_squared_test

```