---
title: "BEACH Data Inventory"
author: "Dominick Lemas"
date: "09/02/2021"
output: html_document

---

```{r, include=FALSE}
##-------------- 
# **************************************************************************** #
# ***************                Project Overview              *************** #
# **************************************************************************** #

# Author:            Dominick Lemas
# Start Date:        Feb 22, 2021 
# Date Modify:       Oct 18, 2020
# IRB:               
#                   
#
# version: R version 4.0.2 (2020-06-22)
# version: Rstudio version Version 1.3.959 

# **************************************************************************** #
# ***************                Description                   *************** #
# **************************************************************************** #

# PLAN: Access redcap via API and pull/format/clean data for downstream analysis.
# Note: vpn must be active

```


```{r, message=FALSE}

# **************************************************************************** #
# ***************                Library                       *************** #
# **************************************************************************** #

library(keyringr)
library(redcapAPI)
library(REDCapR)
library(readxl)
library(tidyverse)
source("~/BEACH-reports/code/utils.R")

```

```{r, message=FALSE}

# API & URL
#----------
url <- "https://redcap.ctsi.ufl.edu/redcap/api/"
token=get_API_token("beach_api")


# PULL REPORT
#------------

url <- "https://redcap.ctsi.ufl.edu/redcap/api/"
formData <- list("token"=token,
    content='report',
    format='json',
    report_id='9356',     # 3rd Trimester
    csvDelimiter='',
    rawOrLabel='raw',
    rawOrLabelHeaders='raw',
    exportCheckboxLabel='false',
    returnFormat='json'
)
response <- httr::POST(url, body = formData, encode = "form")
result <- httr::content(response)
# print(result)

# CONVERT LIST to TIBBLE
#-----------------------

result_tib <- result %>% unlist(recursive = FALSE) %>% 
    enframe() %>% 
    unnest()



```

