---
title: "anaylzeCurrent_Particpant"
author: "Yasmine Gillespie"
date: '2022-10-23'
output: html_document
---

```{r, include=FALSE}
##-------------- 
# **************************************************************************** #
# ***************                Project Overview              *************** #
# **************************************************************************** #

# Author:      Dominick Lemas
# Date:        Nov 17, 2020 
# Modify:      
# IRB:         UFHealth Early Life Exposures and Pediatric Outcomes (IRB201601899) 

# version: R version 4.0.2 (2020-06-22)
# version: Rstudio version Version 1.3.959 

# **************************************************************************** #
# ***************                Description                   *************** #
# **************************************************************************** #

# PLAN: Access redcap via API and pull/format/clean data for downstream analysis.
# Note: vpn must be active

# Next steps
#- function to call the IDs and events
#- function to batch pull EHR data by year/event and combine into final dataset. 


```

```{r, message=FALSE,warning=FALSE, echo = FALSE}

# **************************************************************************** #
# ***************                Library                       *************** #
# **************************************************************************** #

knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
library(tidyverse)
library(dplyr)
library(flextable)
library(gt)
library(formattable)
library(gtsummary)
library(ggplot2)
library(ggrepel)
library(keyringr)
library(readxl)
library(redcapAPI)
library(REDCapR)
library(vtree)
library(vistime)
library(labelled)
library(plyr)
library(plotly)
library(tidyquant)
library(readr)
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
load("~/BEACH-reports/data/raw/Current_Particpant_raw.RData")
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
CP_raw <- CP_raw[ -c(2:4) ]

```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#renaming
names(CP_raw)[2] <- "Random_Contact"
names(CP_raw)[3] <- "Prescreen_Survey"
names(CP_raw)[4] <- "Phone_Screen"
names(CP_raw)[5] <- "IDR"
names(CP_raw)[6] <- "Consent"
names(CP_raw)[7] <- "Complete"
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#recoding
CP_raw=CP_raw %>%
  mutate(beachphone_hear_about_us=recode(beachphone_hear_about_us,
                              "1"="Flyer",
                              "2"="Radio",
                              "3"="Social Media",
                              "4"="Newspaper",
                              "5"="Word-of-mouth",
                              "6"="Other"
                               ))


CP_raw=CP_raw %>%
  mutate(beach_learn_about_study=recode(beach_learn_about_study,
                              "1"="Flyer",
                              "2"="Physician",
                              "3"="Social Media",
                              "4"="Mail",
                              "5"="Other"
                               ))
                              
```


##Phone_Screening
```{r, message=FALSE,warning=FALSE, echo = FALSE}
#sort by phone screen participants
Phone_Screen= filter(CP_raw, Phone_Screen == 1)
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#join columns into Recruitment column for how participant found study
Phone_Screen$Recruitment = coalesce(Phone_Screen$beachphone_hear_about_us, Phone_Screen$beach_learn_about_study, Phone_Screen$IDR)

#recoding if participants didn't complete IDR
Phone_Screen=Phone_Screen %>%
  mutate(Recruitment=recode(Recruitment,
                              "0"="Incomplete"
                            ))

```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#join columns for BMI
Phone_Screen$BMI = coalesce(Phone_Screen$beach_final_bmi, Phone_Screen$beachphone_prepreg_bmi)
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#removing extra columns
Phone_Screen <- Phone_Screen[ -c(9,11,13,14,15) ]
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#recoding
Phone_Screen=Phone_Screen %>%
  mutate(bmi_analysis_prepregnant=recode(bmi_analysis_prepregnant,
                              "1"="Normal",
                              "2"="Overweight",
                              "3"= "Obese"
                               ))
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#renaming and recoding, selecting out columns for BMI and age
Phone_Screen_age_bmi=Phone_Screen %>%
  select(test_id,
         beachphone_age,
         BMI,
       bmi_analysis_prepregnant,
       Recruitment,
       Random_Contact,
       Prescreen_Survey,
       Phone_Screen,
       IDR,
       Consent,
       Complete,
       beachphone_pass_fail
       )%>%
  
   mutate( age_groups =  beachphone_age) %>%
   mutate(Age_grouping = case_when((age_groups <= 25) ~ "18-25",
                                  (age_groups >25 & age_groups <= 30) ~ "26-30",
                                 (age_groups >30 & age_groups <= 35) ~ "31-35",
                                 (age_groups >35 & age_groups <= 40) ~ "36-40",
                                  (age_groups > 40) ~ "> 40"))%>%
   mutate(prepreg_bmi = BMI)%>%
   mutate(Bmi_grouping = case_when((prepreg_bmi >29) ~ "Obese",
                                  (prepreg_bmi >26 & prepreg_bmi<29) ~ "Overweight",
                                  (prepreg_bmi <26) ~ "Normal"))%>%
  select(test_id, Age_grouping,Bmi_grouping, bmi_analysis_prepregnant, Recruitment, Consent,Complete, beachphone_pass_fail, Random_Contact,Prescreen_Survey,Phone_Screen, IDR)

```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#join columns for BMI
Phone_Screen_age_bmi$BMI_Type = coalesce(Phone_Screen_age_bmi$Bmi_grouping, Phone_Screen_age_bmi$bmi_analysis_prepregnant)
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#remove extra columns
Phone_Screen_age_bmi <- Phone_Screen_age_bmi[ -c(3,4) ]
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#recoding
Phone_Screen_age_bmi=Phone_Screen_age_bmi %>%
  mutate(Consent=recode(Consent,
                              "0"="No",
                              "1"="Yes"
                            ))

Phone_Screen_age_bmi=Phone_Screen_age_bmi %>%
  mutate(Complete=recode(Complete,
                              "0"="No",
                              "1"="Yes"
                            ))

Phone_Screen_age_bmi=Phone_Screen_age_bmi %>%
  mutate(Random_Contact=recode(Random_Contact,
                              "0"="No",
                              "1"="Yes"
                            ))

Phone_Screen_age_bmi=Phone_Screen_age_bmi %>%
  mutate(Prescreen_Survey=recode(Prescreen_Survey,
                              "0"="No",
                              "1"="Yes"
                            ))

Phone_Screen_age_bmi=Phone_Screen_age_bmi %>%
  mutate(Phone_Screen=recode(Phone_Screen,
                              "0"="No",
                              "1"="Yes"
                            ))

Phone_Screen_age_bmi=Phone_Screen_age_bmi %>%
  mutate(IDR=recode(IDR,
                              "0"="No",
                              "1"="Yes"
                            ))

Phone_Screen_age_bmi=Phone_Screen_age_bmi %>%
  mutate(beachphone_pass_fail=recode(beachphone_pass_fail,
                              "1"="Pass",
                              "2"="Fail",
                              "3"="Incomplete"
                            ))

```

###Random Contact

#Table 1

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#age gropuing for random contact
vtree(Phone_Screen_age_bmi, "Random_Contact Age_grouping", palette = 3, sortfill = TRUE, horiz=FALSE)
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#BMI grouping for random contact
vtree(Phone_Screen_age_bmi, "Random_Contact BMI_Type", palette = 3, sortfill = TRUE, horiz=FALSE)
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#recruitment outcomes for random contact
vtree(Phone_Screen_age_bmi, "Random_Contact Consent", palette = 3, sortfill = TRUE, horiz=FALSE)
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#recruitment outcomes for random contact
vtree(Phone_Screen_age_bmi, "Random_Contact Complete", palette = 3, sortfill = TRUE, horiz=FALSE)
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#recruitment outcomes for random contact
vtree(Phone_Screen_age_bmi, "Random_Contact beachphone_pass_fail", palette = 3, sortfill = TRUE, horiz=FALSE)
```

#anaylsis
```{r, message=FALSE,warning=FALSE, echo = FALSE}
#select out columns for analysis
Random_Contact = select(filter(Phone_Screen_age_bmi, Random_Contact %in% c("Yes")), c(Random_Contact,BMI_Type,Age_grouping,Consent,Complete, beachphone_pass_fail))
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
Random_Contact_ana <- na.omit(Random_Contact) 

```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#chi squared for random contact age grouping
chisq.test(x = table(Random_Contact_ana$Random_Contact, Random_Contact_ana$Age_grouping))
# X^2= 14.286
# p= 0.002541
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#chi squared for random contact BMI
chisq.test(x = table(Random_Contact_ana$Random_Contact, Random_Contact_ana$BMI_Type))
# X^2= 9.7014
# p= 0.01072
```

###PreScreen

#Table 1

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#filter  for prescreen survey
Just_Pre_Screen= filter(Phone_Screen_age_bmi, Random_Contact == "No" & Prescreen_Survey == "Yes")
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#age grouping for prescreen survey
vtree(Just_Pre_Screen, "Prescreen_Survey Age_grouping", palette = 3, sortfill = TRUE, horiz=FALSE)
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#BMI for prescreen survey
vtree(Just_Pre_Screen, "Prescreen_Survey BMI_Type", palette = 3, sortfill = TRUE, horiz=FALSE)
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#recruitment outcomes for prescreen 
vtree(Just_Pre_Screen, "Prescreen_Survey Consent", palette = 3, sortfill = TRUE, horiz=FALSE)
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#recruitment outcomes for prescreen
vtree(Just_Pre_Screen, "Prescreen_Survey Complete", palette = 3, sortfill = TRUE, horiz=FALSE)
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#recruitment outcomes for prescreen
vtree(Just_Pre_Screen, "Prescreen_Survey beachphone_pass_fail", palette = 3, sortfill = TRUE, horiz=FALSE)
```

#anaylsis

```{r, message=FALSE,warning=FALSE, echo = FALSE}
Just_Pre_Screen_ana <- na.omit(Just_Pre_Screen) 
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#chi squared for prescreen age grouping
chisq.test(x = table(Just_Pre_Screen_ana$Prescreen_Survey, Just_Pre_Screen_ana$Age_grouping))
# X^2= 40.22
# p= 3.897e-08
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#chi squared for prescreen BMI
chisq.test(x = table(Just_Pre_Screen_ana$Prescreen_Survey, Just_Pre_Screen_ana$BMI_Type))
# X^2= 30.729
# p= 2.125e-07
```


#Phonescreen

#Table 1

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#filter for phone screen
Just_Phone_Screen= filter(Phone_Screen_age_bmi, Random_Contact == "No" & Prescreen_Survey == "No")
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#age grouping for phone screen
vtree(Just_Phone_Screen, "Phone_Screen Age_grouping", palette = 3, sortfill = TRUE, horiz=FALSE)
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#BMI grouping for phone screen
vtree(Just_Phone_Screen, "Phone_Screen BMI_Type", palette = 3, sortfill = TRUE, horiz=FALSE)
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#recruitment outcomes for phone screen
vtree(Just_Phone_Screen, "Phone_Screen Consent", palette = 3, sortfill = TRUE, horiz=FALSE)
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#recruitment outcomes for phone screen
vtree(Just_Phone_Screen, "Phone_Screen Complete", palette = 3, sortfill = TRUE, horiz=FALSE)
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#recruitment outcomes for phone screen
vtree(Just_Phone_Screen, "Phone_Screen beachphone_pass_fail", palette = 3, sortfill = TRUE, horiz=FALSE)
```

#anaylsis
```{r, message=FALSE,warning=FALSE, echo = FALSE}
Just_Phone_Screen_ana <- na.omit(Just_Phone_Screen) 
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#chi squared for phone screen age
chisq.test(x = table(Just_Phone_Screen_ana$Phone_Screen, Just_Phone_Screen_ana$Age_grouping))
# X^2= 13.635
# p= 0.003447
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#chi squared for phone screen BMI
chisq.test(x = table(Just_Phone_Screen_ana$Phone_Screen, Just_Phone_Screen_ana$BMI_Type))
# X^2= 30.952
# p= 1.9e-07
```

###Table 2

##Eligible based on Recruitment 
```{r, message=FALSE,warning=FALSE, echo = FALSE}
#filter for participants who completed phone screen
Eligible_Pass= filter(Phone_Screen_age_bmi, beachphone_pass_fail == "Pass")
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#age grouping for each recruitment type
vtree(Eligible_Pass, "Recruitment BMI_Type", palette = 3, sortfill = TRUE, horiz=FALSE)
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#BMI grouping for each recruitment type
vtree(Eligible_Pass, "Recruitment Age_grouping", palette = 3, sortfill = TRUE, horiz=FALSE)
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#recruitment outcomes for each recruitment type
vtree(Eligible_Pass, "Recruitment beachphone_pass_fail", palette = 3, sortfill = TRUE, horiz=FALSE)
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#recruitment outcomes for each recruitment type
vtree(Eligible_Pass, "Recruitment Consent", palette = 3, sortfill = TRUE, horiz=FALSE)
```

#anaylsis
#Table 2
```{r, message=FALSE,warning=FALSE, echo = FALSE}
All_Pass= Eligible_Pass
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
Allrecords <- na.omit(All_Pass) 
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#chi squared for age groups for eligible participants 
chisq.test(Allrecords$Recruitment, Allrecords$Age_grouping, correct=FALSE)
#X^2=18.795
#p=0.09361
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#chi squared for BMI for eligible participants
chisq.test(Allrecords$Recruitment, Allrecords$BMI_Type, correct=FALSE)
#X^2=6.1512
#p=0.4065
```

###Table 3

#Facebook vs Flyers BMI
```{r, message=FALSE,warning=FALSE, echo = FALSE}
Recruitment_ana = select(filter(Allrecords, Recruitment %in% c("Social Media","Flyer"), Consent %in% c("Yes")), c(Recruitment,Age_grouping, BMI_Type, Consent))
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#recruitment methods and BMI for consented participants
vtree(Recruitment_ana, "Recruitment Consent BMI_Type", palette = 3, sortfill = TRUE, horiz=FALSE)
```

#anaylsis
```{r, message=FALSE,warning=FALSE, echo = FALSE}
#chi squared for consented participants
chisq.test(Recruitment_ana$Recruitment, Recruitment_ana$BMI_Type, correct=FALSE)
#X^2=2.4557
#p=0.2929
```



