---
title: "Blood Metabolomics"
author: "Dominick Lemas"
date: "11/15/2022"
output: html_document

---

```{r, include=FALSE}
##-------------- 
# **************************************************************************** #
# ***************                Project Overview              *************** #
# **************************************************************************** #

# Author:            Dominick J. Lemas
# Start Date:        10/04/2022 
# Date Modify:       
# Project:           The Breastfeeding and EArly Child Health
# IRB:               IRB201601034
#                   
#
# version: R version 4.0.2 (2020-06-22)
# version: Rstudio version Version 1.3.959 

# **************************************************************************** #
# ***************                Description                   *************** #
# **************************************************************************** #

# NOTE: This script consumes data that was generated by:
# ~/code/get_data/get_reportData_21221.Rmd
# ~/code/process_data/format_reportData_21221_NIHenrollment.Rmd

# PLAN: Complete NIH Enrollment Table.

# project_name="The Breastfeeding and EArly Child Health Study"
# irb_number="IRB201601034"
# upstream_code="~/code/process_data/format_reportData_21221_NIHenrollment.Rmd"
# report_id<-21221L
# report_name= "BEACH Study Overview"
# input_file="21221_NIHenrollment_clean.RData"

```


```{r, message=FALSE,include=FALSE}

# **************************************************************************** #
# ***************                Library                       *************** #
# **************************************************************************** #


library(tidyverse)
library(quantreg)



```

```{r, message=FALSE,include=FALSE}

# **************************************************************************** #
# ***************              Load/Trim Data                  *************** #
# **************************************************************************** #

metab <- read_excel("~/BEACH-reports/data/raw/TMAO-Choline-Betaine-Lemas-POS_Short_BMI.XLS",
                    col_types = c("text","text","numeric","numeric","numeric","numeric","numeric"))

# linear model

fit_tmao = lm(tmao_ngmL~bmi, data = metab);summary(fit_tmao)
plot(metab$bmi,metab$tmao_ngmL)

fit_tmao2 = lm(tmao_ngmL2~bmi, data = metab);summary(fit_tmao2)
plot(metab$bmi,metab$tmao_ngmL2)

# quantile regression
fit_tmao = rq(tmao_ngmL~bmi, data = metab);summary(fit_tmao)

plot(tmao_ngmL~bmi, data = metab, pch = 16, main = "mpg ~ wt")
abline(lm(tmao_ngmL~bmi, data = metab), col = "red", lty = 2)
abline(rq(tmao_ngmL~bmi, data = metab), col = "blue", lty = 2)
legend("topright", legend = c("lm", "rq"), col = c("red", "blue"), lty = 2)

# filter to include 

metab_filter=metab %>%
  filter(bmi<=20 | bmi >=30) %>%
  filter(bmi<=35)

fit_tmao2 = lm(tmao_ngmL2~bmi, data = metab_filter);summary(fit_tmao2)
plot(metab_filter$bmi,metab_filter$tmao_ngmL2)


```

#### __Project Details__
Title: `r project_name`  
IRB Number: `r irb_number`  
Report Name (source-data): `r report_name`  
Report ID (source-data): `r report_id`  
Upstream Code: `r upstream_code`  
Input Data: `r input_file`

#### __Data Description__


```{r, message=FALSE,echo=FALSE}

# **************************************************************************** #
# ***************              Data Labels                     *************** #
# **************************************************************************** #

# gender

ds_lu_gender <- tibble::tribble(
  ~input,   ~displayed            ,
  "1"   ,  "Male"               ,
  "2"   ,  "Female"                 ,
  "3"   ,  "Unknown/Not Reported"
)

# knitr::kable(ds_lu_gender, caption = "Gender Mapping")

# race

ds_lu_race <- tibble::tribble(
  ~input , ~displayed                                   ,
  "NativeAmerican"    , "American Indian/Alaska Native"              ,
  "Asian"             , "Asian",
  "PacificIsland"    , "Native Hawaiian or Other Pacific Islander"  ,
  "Black"    , "Black or African American"                  ,
  "White"    , "White"                                      ,
  "M"    , "More than One Race"                         ,
  "NA"    , "Unknown or Not Reported"
)

# knitr::kable(ds_lu_race, caption = "Race Mapping")

# ethnicity

ds_lu_ethnicity <- tibble::tribble(
  ~input,   ~displayed                      ,
  "1"   ,  "Not Hispanic or Latino"         ,
  "2"   ,  "Hispanic or Latino"             ,
  "3"   ,  "Unknown/Not Reported Ethnicity"
)
# knitr::kable(ds_lu_ethnicity, caption = "Ethnicity Mapping")

```


```{r, echo=FALSE}

# **************************************************************************** #
# ***************         NIH enrollment table                 *************** #
# **************************************************************************** #

ds_summary_long <- codified::table_nih_enrollment(
  d              = ds,
  d_lu_gender    = ds_lu_gender,
  d_lu_race      = ds_lu_race,
  d_lu_ethnicity = ds_lu_ethnicity
)

knitr::kable(ds_summary_long, caption = "Counts of Each Subgroup")



codified::table_nih_enrollment_pretty(
  d              = ds,
  d_lu_gender    = ds_lu_gender,
  d_lu_race      = ds_lu_race,
  d_lu_ethnicity = ds_lu_ethnicity
)
```

