---
title: "Get RedCap Data: BEACH Study Overview Report"
author: "Dominick J. Lemas"
date: "07/19/2022"
output: html_document

---

```{r, include=FALSE}
##-------------- 
# **************************************************************************** #
# ***************                Project Overview              *************** #
# **************************************************************************** #

# Author:            Dominick J. Lemas
# Start Date:        07/19/2022 
# Date Modify:       10/18/2022
# Project:           The Breastfeeding and EArly Child Health Study
# IRB:               IRB201601034
#                   
#
# version: R version 4.0.2 (2020-06-22)
# version: Rstudio version Version 1.3.959 

# **************************************************************************** #
# ***************                Description                   *************** #
# **************************************************************************** #

# PLAN: Access redcap via API and pull/format/clean data for downstream analysis.
# Note: vpn must be active

# keyringr must be installed: https://cran.r-project.org/web/packages/keyringr/vignettes/Avoiding_plain_text_passwords_in_R_with_keyringr.html

project_name="The Breastfeeding and EArly Child Health Study"
irb_number="IRB201601034"

```

```{r, message=FALSE, include=FALSE}

# **************************************************************************** #
# ***************                Library                       *************** #
# **************************************************************************** #

library(keyringr)
library(redcapAPI)
library(REDCapR)
library(knitr)
library(gt)
library(dplyr)
library(tidyverse)
# library(ezknitr)
source("~/BEACH-reports/code/utils/utils.R")

```

### RedCap/BEACH Data

```{r, message=FALSE,include=FALSE}

# **************************************************************************** #
# ***************              Extract Data                    *************** #
# **************************************************************************** #

# API & URL
#----------
uri <- "https://redcap.ctsi.ufl.edu/redcap/api/"
api_token=get_API_token("beach_api")

# REPORT IDS
#-----------

# Study Overview
report_id<-21221L
report_name= "BEACH Study Overview"


# PULL DATA
#-----------
report_raw <-
  REDCapR::redcap_report(
    redcap_uri = uri,
    token      = api_token,
    report_id  = report_id
  )$data 

report = report_raw %>%
  select(-redcap_event_name,-redcap_repeat_instrument,-redcap_repeat_instance,    # drop out variables not needed
         -clinical_health_update_2wk_v4_042218_complete,
         -health_update_3rd_trimester_v5082518_complete,-biosample_notes,
         -infant_postnatal_care_other,-mom_healthcare_other,
         -exitsurvey_resultsinfo)

```

```{r, message=FALSE,include=FALSE}

# **************************************************************************** #
# ***************              Load/Trim Data                  *************** #
# **************************************************************************** #
  
# create long dataset where each row is a unique mom or infant. The number of 
# rows will represent the total number of mom-baby participants that have signed
# ICF and we have collected data on the infant. 

maternal=report %>%
  mutate(participant_type="maternal") %>%
  select(test_id, participant_type, maternal_sex_nih, mom_ethnicity_nih, 
         maternal_race_nih___1,
         maternal_race_nih___2, maternal_race_nih___3, maternal_race_nih___4,
         maternal_race_nih___5, maternal_race_nih___6) %>%
  rename(ethnicity=mom_ethnicity_nih, 
         race_nih___1=maternal_race_nih___1,
         race_nih___2=maternal_race_nih___2, 
         race_nih___3=maternal_race_nih___3, 
         race_nih___4=maternal_race_nih___4,
         race_nih___5=maternal_race_nih___5, 
         race_nih___6=maternal_race_nih___6)

data = maternal  %>% 
  gather("race", "value", race_nih___1:race_nih___6) %>%
  filter(value==1) %>%
  mutate(race=recode_factor(race,
                                     "race_nih___1" = "NativeAmerican", 
                                     "race_nih___2" = "Asian", 
                                     "race_nih___3" = "Black", 
                                     "race_nih___4" = "PacificIsland", 
                                     "race_nih___5" = "White",
                                     "race_nih___6" = "NA")) %>%
  select(-value)

data$combined = paste(data$test_id, data$participant_type)
data$race=as.character(data$race)
data$race[duplicated(data$combined) | duplicated(data$combined, fromLast = TRUE)] <- "M"
data = data[!duplicated(data$combined),]
data <- data %>%
  mutate(
    race = case_when(
      race == 'NA' ~ 'Unknown/Missing',
      race %in% c('Black', 'White') ~ race,
      TRUE ~ 'Other'
    ),
    ethnicity = case_when(
      ethnicity == 1 ~ 'Non-Hispanic',
      ethnicity == 2 ~ 'Hispanic',
      ethnicity == 3 ~ 'Unknown/Missing',
      TRUE ~ as.character(ethnicity)  
    )
  ) %>%
  select(race, ethnicity)

BEACH_race_count <- data %>%
  dplyr::count(race) %>%
  mutate(Percentage = n / sum(n) * 100) %>%
  rename(Race = race, Count = n)

BEACH_ethnicity_count <- data %>%
  dplyr::count(ethnicity) %>%
  mutate(Percentage = n / sum(n) * 100) %>%
  rename(Ethnicity = ethnicity, Count = n)

```

### UFHealth/Share Drive

```{r, message=FALSE,include=FALSE}

# **************************************************************************** #
# ***************              Extract Data                    *************** #
# **************************************************************************** #

report_raw <- read.csv("Z:/FACULTY/DJLEMAS/EHR_Data/raw/READ_ONLY_DATASETS/10year_data/2021/dataset_09_2021/baby_mom_at_birth_with_payer.csv") 

report = report_raw %>%
  select(race_mom, ethnicity_mom)

```

```{r, message=FALSE,include=FALSE}
# **************************************************************************** #
# ***************              Load/Trim Data                  *************** #
# **************************************************************************** #

data <- report %>%
  rename(race=race_mom,
         ethnicity=ethnicity_mom) %>%
  mutate(
    race = case_when(
      race %in% c('/?', 'UNKNOWN', 'PATIENT REFUSED') ~ 'Unknown/Missing',
      race == 'BLACK' ~ 'Black',
      race == 'WHITE' ~ 'White',
      TRUE ~ 'Other'
    ),
    ethnicity = case_when(
      ethnicity %in% c('PATIENT REFUSED', 'UNKNOWN') ~ 'Unknown/Missing',
      ethnicity == 'HISPANIC' ~ 'Hispanic',
      ethnicity == 'NOT HISPANIC' ~ 'Non-Hispanic',
      TRUE ~ ethnicity
    )
  )

UF_race_count <- data %>%
  dplyr::count(race) %>%
  mutate(Percentage = n / sum(n) * 100) %>%
  rename(Race = race, Count = n)

UF_ethnicity_count <- data %>%
  dplyr::count(ethnicity) %>%
  mutate(Percentage = n / sum(n) * 100) %>%
  rename(Ethnicity = ethnicity, Count = n)

```

### Florida Charts-Alachua Data and OneFlorida Data

```{r, message=FALSE,include=FALSE}
# **************************************************************************** #
# ***************       Manually Add Data from Online          *************** #
# **************************************************************************** #

#Florida Charts Alachua County (AC), 2021 https://www.flhealthcharts.gov/ChartsDashboards/rdPage.aspx?rdReport=PregnancyandYoungChild.Report

AC_race_count <- data.frame(
  Race = c("Black", "Other", "Unknown/Missing", "White"),
  Count = c(14686, 7338, NA, 47905)
)
AC_race_count <- AC_race_count %>%
  mutate(Percentage = Count / sum(Count, na.rm = TRUE) * 100)


AC_ethnicity_count <- data.frame(
  Ethnicity = c("Hispanic", "Non-Hispanic", "Unknown/Missing"),
  Count = c(9381, 60548, NA)
)
AC_ethnicity_count <- AC_ethnicity_count %>%
  mutate(Percentage = Count / sum(Count, na.rm = TRUE) * 100)



#OneFlorida - 
FL_race_count <- data.frame(
  Race = c("Black", "Other", "Unknown/Missing", "White"),
  Count = c(10109, 6550, 1165, 23929)
)
FL_race_count <- FL_race_count %>%
  mutate(Percentage = Count / sum(Count, na.rm = TRUE) * 100)


FL_ethnicity_count <- data.frame(
  Ethnicity = c("Hispanic", "Non-Hispanic", "Unknown/Missing"),
  Count = c(11158, 25532, 513)
)
FL_ethnicity_count <- FL_ethnicity_count %>%
  mutate(Percentage = Count / sum(Count, na.rm = TRUE) * 100)


```


### Table

```{r, message=FALSE,include=FALSE}
# **************************************************************************** #
# ***************    Create Demographic Comparison Table       *************** #
# **************************************************************************** #
combined_race <- bind_rows(
  BEACH_race_count %>% mutate(Source = "BEACH"),
  UF_race_count %>% mutate(Source = "UF"),
  AC_race_count %>% mutate(Source = "Alachua"),
  FL_race_count %>% mutate(Source = "OneFlorida")
) %>%
  mutate(Count_Percentage = sprintf("%d (%.2f%%)", Count, Percentage),
         Race = ifelse(Race == "Unknown/Missing", "Unknown/Missing Race", Race)) 

combined_ethnicity <- bind_rows(
  BEACH_ethnicity_count %>% mutate(Source = "BEACH"),
  UF_ethnicity_count %>% mutate(Source = "UF"),
  AC_ethnicity_count %>% mutate(Source = "Alachua"),
  FL_ethnicity_count %>% mutate(Source = "OneFlorida")
) %>%
  mutate(Count_Percentage = sprintf("%d (%.2f%%)", Count, Percentage),
         Ethnicity = ifelse(Ethnicity == "Unknown/Missing", "Unknown/Missing Ethnicity", Ethnicity)) 

combined_table <- bind_rows(
  combined_race %>% rename(Demographic = Race),
  combined_ethnicity %>% rename(Demographic = Ethnicity)
) %>%
  select(Demographic, Source, Count_Percentage) %>%
  pivot_wider(names_from = Source, values_from = Count_Percentage)

desired_order <- c("White", "Black", "Other", "Unknown/Missing Race", "Hispanic", "Non-Hispanic", "Unknown/Missing Ethnicity")

combined_table <- combined_table %>%
  arrange(factor(Demographic, levels = desired_order))

gt_table <- combined_table %>%
  gt() %>%
  tab_spanner(
    label = "Location",
    columns = matches("BEACH|UF|Alachua|OneFlorida")
  ) %>%
  tab_header(
    title = "Demographic Comparisons for the BEACH Study"
  )

print(gt_table)
gtsave(gt_table, "demo_table.docx")

```

