---
title: "Fetch/Format Diet Records"
author: "Dominick J. Lemas"
date: "10/11/2023"
output: html_document

---

```{r, include=FALSE}
##-------------- 
# **************************************************************************** #
# ***************                Project Overview              *************** #
# **************************************************************************** #

# Author:            Dominick J. Lemas
# Start Date:        10/11/2023 
# Date Modify:       
# Project:           The Breastfeeding and EArly Child Health Study
# IRB:               IRB201601034
#                   
#
# R version 4.3.1 (2023-06-16 ucrt) -- "Beagle Scouts"
# Copyright (C) 2023 The R Foundation for Statistical Computing
# Platform: x86_64-w64-mingw32/x64 (64-bit) 

# **************************************************************************** #
# ***************                Description                   *************** #
# **************************************************************************** #

# import diet record and format for import to redcap and downstream analysis

project_name="The Breastfeeding and EArly Child Health Study"
irb_number="IRB201601034"

```

```{r, message=FALSE, include=FALSE}

# **************************************************************************** #
# ***************                Library                       *************** #
# **************************************************************************** #


library(tidyverse)
source("~/BEACH-reports/code/utils/utils.R")

```

```{r, message=FALSE,include=FALSE}

# **************************************************************************** #
# ***************              Demo Data                    *************** #
# **************************************************************************** #


# Load data
#-----------

# load("~/BEACH-reports/data/demo/NHANES_19992000.rda")
# NHANES_19992000
# list(NHANES_19992000)
# 
# NHANES_19992000$WJFRT

```

```{r, message=FALSE,include=FALSE}

# **************************************************************************** #
# ***************           Load Experimental Data Local       *************** #
# **************************************************************************** #


data_wide <- read_csv("C:/Users/djlemas/Dropbox (UFL)/02_Projects/BEACH_STUDY/10_Diet/BLS030A_Third_Trimester_example.csv") %>%
  rename(item_name="Item Name",
          quanity=Quantity,
          measure=Measure,
          wgt_g="Wgt (g)",
          cals_kcal="Cals (kcal)",
          fatcals_kcal="FatCals (kcal)",
          satcals_kcal="SatCals (kcal)",
          prot_g="Prot (g)",
          carb_g="Carb (g)",
          totfib_g="TotFib (g)",
          totsolfib_g="TotSolFib (g)",
          fib16_g="Fib(16) (g)",
          solfib16_g="SolFib(16) (g)",
          sugar_g="Sugar (g)",
          sugadd_g="SugAdd (g)",
          monsac_g="MonSac (g)",
          disacc_g="Disacc (g)",
          ocarb_g="OCarb (g)",
          fat_g="Fat (g)",
          satfat_g="SatFat (g)",
          monofat_g="MonoFat (g)",
          polyfat_g="PolyFat (g)",
          transfat_g="TransFat (g)",
          chol_mg="Chol (mg)",
          water_g="Water (g)",
          vita_iu="Vit A-IU (IU)",
          vita_mcg="Vit A-RAE (mcg)",
          caroten_mcg="Caroten (mcg)",
          retinol_mcg="Retinol (mcg)",
          betacaro_mcg="BetaCaro (mcg)",
          vitb1_mg="Vit B1 (mg)",
          vitb2_mg="Vit B2 (mg)",
          vitb3_mg="Vit B3 (mg)",
          vitb3_ne_mg="Vit B3-NE (mg)",
          vitb6_mg="Vit B6 (mg)",
          vitb12_mcg="Vit B12 (mcg)",
          biot_mcg="Biot (mcg)",
          vitc_mg="Vit C (mg)",
          vitd_iu="Vit D-IU (IU)",
          vitd_mcg="Vit D-mcg (mcg)",
          vite_mg="Vit E-a-Toco (mg)",
          folate_mcg="Folate (mcg)",
          foldfe_mcg="Fol-DFE (mcg DFE)",
          vitk_mcg="Vit K (mcg)",
          panto_mg="Panto (mg)",
          calc_mg="Calc (mg)",
          chrom_mcg="Chrom (mcg)",
          copp_mg="Copp (mg)",
          flour_mg="Fluor (mg)",
          iodine_mcg="Iodine (mcg)",
          iron_mg="Iron (mg)",
          magn_mg="Magn (mg)",
          mang_mg="Mang (mg)",
          moly_mcg="Moly (mcg)",
          phos_mg="Phos (mg)",
          pot_mg="Pot (mg)",
          sel_mcg="Sel (mcg)",
          sod_mg="Sod (mg)",
          zinc_mg="Zinc (mg)",
          omega3_g="Omega3 (g)",
          omega6_g="Omega6 (g)",
          alc_g="Alc (g)",
          caff_mg="Caff (mg)",
          chln_mg="Chln (mg)")


data_long=gather(data_wide, key="nutrient", value="value", wgt_g:chln_mg) %>%
  mutate(value = replace(value, value == "--", NA))

# names(data)

write_csv(data_long,"C:/Users/djlemas/Dropbox (UFL)/02_Projects/BEACH_STUDY/10_Diet/BLS030A_Third_Trimester_import.csv" )

```

