---
title: "anaylzeRecruitment"
author: "Yasmine Gillespie"
date: '2022-11-05'
output: html_document
---

```{r, include=FALSE,echo=FALSE}
##-------------- 
# **************************************************************************** #
# ***************                Project Overview              *************** #
# **************************************************************************** #

# Author:      Yasmine Gillespie
# Date:        Oct 25, 2022 
# Modify:      
# IRB:         UFHealth Early Life Exposures and Pediatric Outcomes (IRB201601899) 

# version: R version 4.2.2 (2022-10-31)
# version: Rstudio version Version 1.3.959 

# **************************************************************************** #
# ***************                Description                   *************** #
# **************************************************************************** #

# PLAN: Access redcap via API and pull/format/clean data for downstream analysis.
# Note: vpn must be active

# Next steps
#- function to call the IDs and events
#- function to batch pull EHR data by year/event 


```

```{r, message=FALSE,warning=FALSE, echo = FALSE}

# **************************************************************************** #
# ***************                Library                       *************** #
# **************************************************************************** #

knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
library(tidyverse)
library(dplyr)
library(flextable)
library(gt)
library(formattable)
library(gtsummary)
library(ggplot2)
library(ggrepel)
library(keyringr)
library(readxl)
library(redcapAPI)
library(REDCapR)
library(vtree)
library(vistime)
library(labelled)
library(plyr)
library(plotly)
library(tidyquant)
library(readr)
```

```{r, message=FALSE,include=FALSE}

# **************************************************************************** #
# ***************              Load Data                       *************** #
# ****************************************************************************#

load("~/BEACH-Reports/output/reports/recruitment/Recruitment_raw.RData")

```


```{r, message=FALSE,warning=FALSE,echo=FALSE}

# **************************************************************************** #
# ***************              Eligible_Pass Data              *************** #
# **************************************************************************** #

#renames the first row containing column titles

names(recruitment_report)[5] <- "Random_Contact"
names(recruitment_report)[6] <- "Prescreen_Survey"
names(recruitment_report)[7] <- "Phone_Screen"
names(recruitment_report)[8] <- "IDR"
names(recruitment_report)[9] <- "Consent"
names(recruitment_report)[10] <- "Complete"
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}

#recodes numerical variables to be clearer for beachphone_hear_about_us, beach_learn_about_study, and IDR variables

recruitment_report=recruitment_report %>%
  mutate(beachphone_hear_about_us=recode(beachphone_hear_about_us,
                              "1"="Flyer",
                              "2"="Radio",
                              "3"="Social Media",
                              "4"="Newspaper",
                              "5"="Word-of-mouth",
                              "6"="Other"
                               ))

recruitment_report=recruitment_report %>%
  mutate(beach_learn_about_study=recode(beach_learn_about_study,
                              "1"="Flyer",
                              "2"="Physician",
                              "3"="Social Media",
                              "4"="Mail",
                              "5"="Other"
                               ))

recruitment_report=recruitment_report %>%
  mutate(IDR=recode(IDR,
                              "1"="IDR"
                            ))

                              
```

```{r, message=FALSE,warning=FALSE,echo=FALSE}

#merge different recruitment methods into one column to fill in N/A blanks

recruitment_report$Recruitment = coalesce(recruitment_report$beachphone_hear_about_us, recruitment_report$beach_learn_about_study, recruitment_report$IDR)

```

```{r, message=FALSE,warning=FALSE, echo = FALSE}

#recodes NA to show as incomplete

recruitment_report$Recruitment[is.na(recruitment_report$Recruitment)] <- 0
recruitment_report=recruitment_report %>%
  mutate(Recruitment=recode(Recruitment,
                              "0"="Incomplete"
                            ))

```

```{r, message=FALSE,include=FALSE}

# **************************************************************************** #
# ***************              Save Data Local                 *************** #
# **************************************************************************** #
# Save the data in your local laptop (Github path: /data)

save(list=c("recruitment_report"),file="~/BEACH-Reports/output/reports/recruitment/recruitment_clean.RData")

```
