---
title: "anaylzeExample"
author: "Yasmine Gillespie"
date: '2022-10-25'
output: html_document
---

```{r, include=FALSE,echo=FALSE}
##-------------- 
# **************************************************************************** #
# ***************                Project Overview              *************** #
# **************************************************************************** #

# Author:      Yasmine Gillespie
# Date:        Oct 25, 2022 
# Modify:      
# IRB:         UFHealth Early Life Exposures and Pediatric Outcomes (IRB201601899) 

# version: R version 4.2.2 (2022-10-31)
# version: Rstudio version Version 1.3.959 

# **************************************************************************** #
# ***************                Description                   *************** #
# **************************************************************************** #

# PLAN: Access redcap via API and pull/format/clean data for downstream analysis.
# Note: vpn must be active

# Next steps
#- function to call the IDs and events
#- function to batch pull EHR data by year/event 


```

```{r, message=FALSE,warning=FALSE,echo=FALSE}

# **************************************************************************** #
# ***************                Library                       *************** #
# **************************************************************************** #

knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
library(tidyverse)
library(dplyr)
library(flextable)
library(gt)
library(formattable)
library(gtsummary)
library(ggplot2)
library(ggrepel)
library(keyringr)
library(readxl)
library(redcapAPI)
library(REDCapR)
library(vtree)
library(vistime)
library(labelled)
library(plyr)
library(plotly)
library(tidyquant)
library(readr)
```

```{r, message=FALSE,include=FALSE}

# **************************************************************************** #
# ***************              Load Data                       *************** #
# ****************************************************************************#

load("~/BEACH-Reports/output/reports/recruitment/all_encounters_raw.RData")

```

```{r, message=FALSE,warning=FALSE,echo=FALSE}

# **************************************************************************** #
# ***************              Eligible_Pass Data              *************** #
# **************************************************************************** #

#renames the first row containing column titles

names(Encounter_report)[2] <- "Random_Contact"
names(Encounter_report)[3] <- "Prescreen_Survey"
names(Encounter_report)[4] <- "Phone_Screen"
names(Encounter_report)[5] <- "IDR"
names(Encounter_report)[6] <- "Consent"
names(Encounter_report)[7] <- "Complete"


```

```{r, message=FALSE,warning=FALSE, echo = FALSE}

#recodes numerical variables to be clearer for encounter_type and pass_fail variable

Encounter_report= Encounter_report%>%
  mutate(beach_encounter_type=recode(beach_encounter_type,
                              "1"="email",
                              "2"="phone",
                              "3"="other",
                              "4"="IDR_team",
                               ))
Encounter_report= Encounter_report%>%
  mutate(beachphone_pass_fail=recode(beachphone_pass_fail,
                              "1"="pass",
                              "2"="fail",
                              "3"="incomplete"
                               ))

```

```{r, message=FALSE,include=FALSE}

# **************************************************************************** #
# ***************              Save Data Local                 *************** #
# **************************************************************************** #
# Save the data in your local laptop (Github path: /data)

save(list=c("Encounter_report"),file="~/BEACH-Reports/output/reports/recruitment/Encounter_All_clean.RData")

```