---
title: "anaylzeCurrent_Particpant"
author: "Yasmine Gillespie"
date: '2022-11-10'
output: html_document

---

```{r, include=FALSE,echo=FALSE}
##-------------- 
# **************************************************************************** #
# ***************                Project Overview              *************** #
# **************************************************************************** #

# Author:      Yasmine Gillespie
# Date:        November 17, 2020 
# Modify:      November 10, 2022
# IRB:         The Breastfeeding and EArly Child Health Study
# IRB:         IRB201601899
#
#
# version: R version 4.2.2 (2022-10-31)
# version: Rstudio version Version 1.3.959 

# **************************************************************************** #
# ***************                Description                   *************** #
# **************************************************************************** #

# PLAN: Access redcap via API and pull/format/clean data for downstream analysis.
# Note: vpn must be active

# Next steps
#- function to call the IDs and events
#- function to batch pull EHR data by year/event 


```

```{r, message=FALSE,warning=FALSE,echo = FALSE}

# **************************************************************************** #
# ***************                Library                       *************** #
# **************************************************************************** #

knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
library(tidyverse)
library(dplyr)
library(flextable)
library(gt)
library(formattable)
library(gtsummary)
library(ggplot2)
library(ggrepel)
library(keyringr)
library(readxl)
library(redcapAPI)
library(REDCapR)
library(vtree)
library(vistime)
library(labelled)
library(plyr)
library(plotly)
library(tidyquant)
library(readr)
```

```{r, message=FALSE,include=FALSE}

# **************************************************************************** #
# ***************              Load Data                       *************** #
# **************************************************************************** #

load("~/BEACH-Reports/output/reports/recruitment/Current_Particpant_raw.RData")

```

```{r, message=FALSE,warning=FALSE,echo=FALSE}

# **************************************************************************** #
# ***************              Eligible_Pass Data              *************** #
# **************************************************************************** #

#renames the first row containing column titles

names(CP_report)[2] <- "Random_Contact"
names(CP_report)[3] <- "Prescreen_Survey"
names(CP_report)[4] <- "Phone_Screen"
names(CP_report)[5] <- "IDR"
names(CP_report)[6] <- "Consent"
names(CP_report)[7] <- "Complete"

```

```{r, message=FALSE,warning=FALSE,echo=FALSE}

#recodes numerical variables to be clearer for hear_about_us variable
CP_report=CP_report %>%
  mutate(beachphone_hear_about_us=recode(beachphone_hear_about_us,
                              "1"="Flyer",
                              "2"="Radio",
                              "3"="Social Media",
                              "4"="Newspaper",
                              "5"="Word-of-mouth",
                              "6"="Other"
                               ))
                              
```

```{r, message=FALSE,warning=FALSE,echo=FALSE}

#isolates participants with a beachphone_pass_fail = 1
Eligible_Pass= filter(CP_report, beachphone_pass_fail == 1)

```

```{r, message=FALSE,warning=FALSE,echo=FALSE}

#add beach_final_bmi variable 
Eligible_Pass$BMI = coalesce(Eligible_Pass$beach_final_bmi, Eligible_Pass$beachphone_prepreg_bmi)

```

```{r, message=FALSE,warning=FALSE,echo=FALSE}

#recodes numerical variables for BMI analysis
Eligible_Pass=Eligible_Pass %>%
  mutate(bmi_analysis_prepregnant=recode(bmi_analysis_prepregnant,
                              "1"="Normal",
                              "2"="Overweight",
                              "3"= "Obese"
                               ))

```

```{r, message=FALSE,warning=FALSE,echo=FALSE}

#create table with participants that passed, age, BMI grouping, and how they heard about the study
Eligible_Pass_age_bmi=Eligible_Pass %>%
  select(test_id,
         beachphone_age,
         BMI,
       bmi_analysis_prepregnant,
       beachphone_hear_about_us
       )%>%
  
   mutate( age_groups =  beachphone_age) %>%
   mutate(Age_grouping = case_when((age_groups <= 25) ~ "18-25",
                                  (age_groups >25 & age_groups <= 30) ~ "26-30",
                                 (age_groups >30 & age_groups <= 35) ~ "31-35",
                                 (age_groups >35 & age_groups <= 40) ~ "36-40",
                                  (age_groups > 40) ~ "> 40"))%>%
   mutate(prepreg_bmi = BMI)%>%
   mutate(Bmi_grouping = case_when((prepreg_bmi >29) ~ "Obese",
                                  (prepreg_bmi >26 & prepreg_bmi<29) ~ "Overweight",
                                  (prepreg_bmi <26) ~ "Normal"))%>%
  select(test_id,age_groups, Age_grouping,prepreg_bmi,Bmi_grouping, bmi_analysis_prepregnant, beachphone_hear_about_us)


```

```{r, message=FALSE,warning=FALSE,echo=FALSE}

#BMI type
    #same as BMI_grouping?
Eligible_Pass_age_bmi$BMI_Type = coalesce(Eligible_Pass_age_bmi$Bmi_grouping, Eligible_Pass_age_bmi$bmi_analysis_prepregnant)

```

```{r, message=FALSE,warning=FALSE,echo=FALSE}

#cleaned table with age, how participant found out about study, BMI group 
Eligible_Pass_age_bmi_clean <- Eligible_Pass_age_bmi[ -c(2,4,5,6) ]

```

```{r, message=FALSE,warning=FALSE,echo=FALSE}

names(Eligible_Pass_age_bmi_clean)[4] <- "BMI_grouping"

```


```{r, message=FALSE,warning=FALSE, echo = FALSE}

# **************************************************************************** #
# ***************                 Consent Data                 *************** #
# **************************************************************************** #

#create consent data
CP_Consent= filter(CP_report, Consent == 1)

```

```{r, message=FALSE,warning=FALSE, echo = FALSE}

#adding BMI
CP_Consent$BMI = coalesce(CP_Consent$beach_final_bmi, CP_Consent$beachphone_prepreg_bmi)

```

```{r, message=FALSE,warning=FALSE, echo = FALSE}

#recodes numerical variables for BMI analysis
CP_Consent=CP_Consent %>%
  mutate(bmi_analysis_prepregnant=recode(bmi_analysis_prepregnant,
                              "1"="Normal",
                              "2"="Overweight",
                              "3"= "Obese"
                               ))
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}

#create table with participants that passed, age, BMI grouping, and how they heard about the study
CP_age_bmi=CP_Consent %>%
  select(test_id,
         beachphone_age,
         BMI,
       bmi_analysis_prepregnant,
       beachphone_hear_about_us
       )%>%
  
   mutate( age_groups =  beachphone_age) %>%
   mutate(Age_grouping = case_when((age_groups <= 25) ~ "18-25",
                                  (age_groups >25 & age_groups <= 30) ~ "26-30",
                                 (age_groups >30 & age_groups <= 35) ~ "31-35",
                                 (age_groups >35 & age_groups <= 40) ~ "36-40",
                                  (age_groups > 40) ~ "> 40"))%>%
   mutate(prepreg_bmi = BMI)%>%
   mutate(Bmi_grouping = case_when((prepreg_bmi >29) ~ "Obese",
                                  (prepreg_bmi >26 & prepreg_bmi<29) ~ "Overweight",
                                  (prepreg_bmi <26) ~ "Normal"))%>%
  select(test_id,age_groups, Age_grouping,prepreg_bmi,Bmi_grouping, bmi_analysis_prepregnant, beachphone_hear_about_us)

```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
CP_age_bmi$BMI_Type = coalesce(CP.age.bmi$Bmi_grouping, CP_age_bmi$bmi_analysis_prepregnant)
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
CP_age_bmi_clean <- CP_age_bmi[ -c(2,4,5,6) ]
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}

names(CP_age_bmi_clean)[4] <- "BMI_grouping"

```


```{r, message=FALSE,include=FALSE}

# **************************************************************************** #
# ***************              Save Data Local                 *************** #
# **************************************************************************** #
# Save the data in your local laptop (Github path: /data)

save(list=c("Eligible_Pass_age_bmi_clean"),file="~/BEACH-Reports/output/reports/recruitment/Current_Particpant_clean.RData")

```

