---
title: "getData_current_particpant"
author: "Yasmine Gillespie"
date: '2022-10-23'
output: html_document

---

```{r, include=FALSE}
##--------------
# **************************************************************************** #
# ***************                Project Overview              *************** #
# **************************************************************************** #
# Author:             Hailey Ballard
# Start Date:         October 21, 2021
# Date Modify:        November 4, 2022
# Project:            The Breastfeeding and EArly Child Health Study
# IRB:                IRB201601034
#
# version: R version 4.0.2 (2020-06-22)
# version: Rstudio version Version 1.3.959

# **************************************************************************** #
# ***************                Description                   *************** #
# **************************************************************************** #

# PLAN: Access redcap via API and pull/format/clean data for downstream analysis.
# Note: vpn must be active

# keyringr must be installed: https://cran.r-project.org/web/packages/keyringr/vignettes/Avoiding_plain_text_passwords_in_R_with_keyringr.html


project_name="The Breastfeeding and EArly Child Health Study"
irb_number="IRB201601034"

```


```{r, message=FALSE, include=FALSE}

# **************************************************************************** #
# ***************                Library                       *************** #
# **************************************************************************** #
library(keyringr)
library(redcapAPI)
library(REDCapR)
library(readxl)
library(tidyverse)
source("~/BEACH-reports/code/utils/utils.R")

```

```{r, message=FALSE,include=FALSE}
# Windows
api_token=get_API_token("BEACH-Facebook")

```

```{r, message=FALSE,include=FALSE}
# Mac, you need to store your API code in your keychain first
api_token <- decrypt_kc_pw("Redcap_BEACH_facebook")

```

```{r, message=FALSE,include=FALSE}

# **************************************************************************** #
# ***************              Extract Data                    *************** #
# **************************************************************************** #

# API & URL
#----------
uri <- "https://redcap.ctsi.ufl.edu/redcap/api/"
api_token=get_API_token("beach_api")

        #not sure if either this or the Windows and Mac sections needed

# Total Recruitment
        #correct report title?
#----------
report_id <- 35366
report_name="Total Recruitment"

#PULL DATA
#----------
report_raw <-
  REDCapR::redcap_report(
    redcap_uri = uri,
    token      = api_token,
    report_id  = report_id
  )$data 

```

```{r, message=FALSE,include=FALSE}
# **************************************************************************** #
# ***************              Save Data Local                 *************** #
# **************************************************************************** #
# Save the data in your local laptop (Github path: BEACH-reports)
save(list=c("CP_raw"),file="~/BEACH-Reports/output/reports/recruitment/Current_Particpant_raw.RData")
```