---
title: "anaylze_Recruitment_Age_BMI"
author: "Yasmine Gillespie"
date: "2023-06-02"
output: html_document
---
```{r, include=FALSE}
##-------------- 
# **************************************************************************** #
# ***************                Project Overview              *************** #
# **************************************************************************** #
# Author:      Dominick Lemas
# Date:        Nov 17, 2020 
# Modify:      
# IRB:         UFHealth Early Life Exposures and Pediatric Outcomes (IRB201601899) 
# version: R version 4.0.2 (2020-06-22)
# version: Rstudio version Version 1.3.959 
# **************************************************************************** #
# ***************                Description                   *************** #
# **************************************************************************** #
# PLAN: Access redcap via API and pull/format/clean data for downstream analysis.
# Note: vpn must be active
# Next steps
#- function to call the IDs and events
#- function to batch pull EHR data by year/event and combine into final dataset. 
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
# **************************************************************************** #
# ***************                Library                       *************** #
# **************************************************************************** #
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
library(tidyverse)
library(dplyr)
library(flextable)
library(gt)
library(formattable)
library(gtsummary)
library(ggplot2)
library(ggrepel)
library(keyringr)
library(readxl)
library(redcapAPI)
library(REDCapR)
library(vtree)
library(vistime)
library(labelled)
library(plyr)
library(plotly)
library(tidyquant)
library(readr)
```

#Table 2
```{r, message=FALSE,warning=FALSE, echo = FALSE}
#age grouping for each recruitment type
vtree(Eligible_Pass, "Recruitment Age_grouping", palette = 3, sortfill = TRUE, horiz=FALSE)
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#NW vs OW+Ob
vtree(Eligible_Pass, "Recruitment BMI", palette = 3, sortfill = TRUE, horiz=FALSE)
```

#anaylsis

#Table 2 anaylsis
#age
```{r, message=FALSE,warning=FALSE, echo = FALSE}
CP_table2_Age = select(filter(Eligible_Pass),c(Recruitment, Age_grouping))
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
CP_table2_Age <- na.omit(CP_table2_Age) 
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
chisq.test(CP_table2_Age$Recruitment, CP_table2_Age$Age_grouping, correct=FALSE)
#X^2=18.715
#p=0.09565
```

#BMI
```{r, message=FALSE,warning=FALSE, echo = FALSE}
CP_table2_BMI = select(filter(Eligible_Pass),c(Recruitment, BMI_Type))
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
CP_table2_BMI <- na.omit(CP_table2_BMI) 
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
chisq.test(CP_table2_BMI$Recruitment, CP_table2_BMI$BMI_Type, correct=FALSE)
#X^2=6.229
#p=0.398
```

##NW vs OW +Ob
```{r, message=FALSE,warning=FALSE, echo = FALSE}
CP_table2_BMI2 = select(filter(Eligible_Pass),c(Recruitment, BMI))
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
CP_table2_BMI2 <- na.omit(CP_table2_BMI2) 
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
chisq.test(CP_table2_BMI2$Recruitment, CP_table2_BMI2$BMI, correct=FALSE)
#X^2=6.229
#p=0.398
```



