---
title: "Get RedCap Data: Plasma Metabolomics Report"
author: "Dominick J. Lemas"
date: "04/15/2023"
output: html_document
---

```{r, include=FALSE}
##-------------- 
# **************************************************************************** #
# ***************                Project Overview              *************** #
# **************************************************************************** #

# Author:            Dominick J. Lemas
# Start Date:        04/15/2023 
# Date Modify:       
# Project:           The Breastfeeding and Early Child Health Study
# IRB:               IRB201601034
#                   
#
# R version 4.2.1 (2022-06-23 ucrt) -- "Funny-Looking Kid"
# Copyright (C) 2022 The R Foundation for Statistical Computing
# Platform: x86_64-w64-mingw32/x64 (64-bit)

# **************************************************************************** #
# ***************                Description                   *************** #
# **************************************************************************** #

# PLAN: Access redcap via API and fetch/format/ready data for downstream analysis.
# Note: vpn must be active

# keyringr must be installed: https://cran.r-project.org/web/packages/keyringr/vignettes/Avoiding_plain_text_passwords_in_R_with_keyringr.html

project_name="The Breastfeeding and EArly Child Health Study"
irb_number="IRB201601034"

```

```{r, message=FALSE, include=FALSE}

# **************************************************************************** #
# ***************                Library                       *************** #
# **************************************************************************** #

library(keyringr)
library(redcapAPI)
library(REDCapR)
library(tidyverse)
source("~/plasma-metabolomics/code/utils/utils.R")


```

```{r, message=FALSE,include=FALSE}

# **************************************************************************** #
# ***************              Extract Data                    *************** #
# **************************************************************************** #

# API & URL
#----------
uri <- "https://redcap.ctsi.ufl.edu/redcap/api/"
api_token = get_API_token("beach_api")
#api_token="14BC9225EDC31A7B6B2D069BF7E93954"

# REPORT IDS
#-----------

# Study Overview
report_id<-39840L
report_name= "Plasma Metabolomics and Maternal-Infant Outcomes"


# PULL DATA
#-----------
report_raw <-
  REDCapR::redcap_report(
    redcap_uri = uri,
    token      = api_token,
    report_id  = report_id
  )$data 

# plasma
plasma = report_raw %>%
   select(test_id,metabolite_name,metabolite_units,metabolite_value) %>% drop_na()

# maternal outcomes
maternal = report_raw %>%
   select(test_id,beach_final_bmi,maternal_study_groups,mom_ethnicity_nih,
          maternal_race_nih___1,maternal_race_nih___2,maternal_race_nih___3,
          maternal_race_nih___4,maternal_race_nih___5,maternal_race_nih___6) %>% drop_na() %>%
  rename(maternal_AIAN=maternal_race_nih___1,
         maternal_ASIAN=maternal_race_nih___2,
         maternal_BLACK=maternal_race_nih___3,
         maternal_HAWAII=maternal_race_nih___4,
         maternal_WHITE=maternal_race_nih___5,
         maternal_NA=maternal_race_nih___6)
names(maternal)

# infant outcomes
infant = report_raw %>%
   select(test_id,infant_ethnicity_nih,
          infant_race_nih___1,infant_race_nih___2,infant_race_nih___3,
          infant_race_nih___4,infant_race_nih___5,infant_race_nih___6,
          infant_crc_wt_kg,wt_zscore,inf2wk_gest_age,inf2wk_sex) %>%
  rename(infant_AIAN=infant_race_nih___1,
         infant_ASIAN=infant_race_nih___2,
         infant_BLACK=infant_race_nih___3,
         infant_HAWAII=infant_race_nih___4,
         infant_WHITE=infant_race_nih___5,
         infant_NA=infant_race_nih___6)
names(infant)

# merge datasets
# plasma_infant=left_join(plasma, infant)


```

```{r, message=FALSE, include=FALSE}

# **************************************************************************** #
# ***************                Caroline's Space               *************** #
# **************************************************************************** #

# subset to tmao
tmao=plasma %>%
  filter(metabolite_name=="tmao")

# tmao scatterplot
scatter.smooth(tmao$metabolite_value, col = 'pink', pch = 19, main = 'Scatterplot of TMAO Metabolite Value Index', xlab="patient index", ylab="concentration of TMAO (ng/mL)")

# tmao histogram
hist(tmao$metabolite_value, col='pink', border="white", xlab = 'concentration', main= 'Frequency of TMAO Concentration (ng/mL)')

# subset to choline
choline=plasma %>%
  filter(metabolite_name=="choline")

# choline histograms 
hist(choline$metabolite_value, col = 'pink', border = "white", xlab = 'concentration', main = 'Frequency of Choline Concentration (ng/mL)')

#choline scatterplots
scatter.smooth(choline$metabolite_value, col = 'pink', pch = 19, main = 'Scatterplot of Choline Metabolite Value Index', xlab="patient index", ylab="concentration of choline (ng/mL)")

# subset to betanine
betanine=plasma %>%
  filter(metabolite_name=="betanine")

# betanine histograms 
hist(betanine$metabolite_value, col = 'pink', border = "white", xlab = 'concentration', main = 'Frequency of Betanine Concentration (ng/mL)')


#betanine scatterplots
scatter.smooth(betanine$metabolite_value, col = 'pink', pch = 19, main = 'Scatterplot of Betanine Metabolite Value Index', xlab="patient index", ylab="concentration of betanine (ng/mL)")

# other visualization



# **************************************************************************** #
# ***************              Save Data Local                 *************** #
# **************************************************************************** #

# Save the data in your local laptop (Github path: /data)
save(list=c("report"),file="~/BEACH-reports/data/raw/report_39840.RData")

output_directory="~/BEACH-reports/data/raw/"
output_file_name="report_39840.RData"

```
