---
title: "anaylze_DemographicPhases"
author: "Yasmine Gillespie"
date: "2023-06-02"
output: html_document
---
```{r, include=FALSE}
##-------------- 
# **************************************************************************** #
# ***************                Project Overview              *************** #
# **************************************************************************** #
# Author:      Dominick Lemas
# Date:        Nov 17, 2020 
# Modify:      
# IRB:         UFHealth Early Life Exposures and Pediatric Outcomes (IRB201601899) 
# version: R version 4.0.2 (2020-06-22)
# version: Rstudio version Version 1.3.959 
# **************************************************************************** #
# ***************                Description                   *************** #
# **************************************************************************** #
# PLAN: Access redcap via API and pull/format/clean data for downstream analysis.
# Note: vpn must be active
# Next steps
#- function to call the IDs and events
#- function to batch pull EHR data by year/event and combine into final dataset. 
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
# **************************************************************************** #
# ***************                Library                       *************** #
# **************************************************************************** #
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
library(tidyverse)
library(dplyr)
library(flextable)
library(gt)
library(formattable)
library(gtsummary)
library(ggplot2)
library(ggrepel)
library(keyringr)
library(readxl)
library(redcapAPI)
library(REDCapR)
library(vtree)
library(vistime)
library(labelled)
library(plyr)
library(plotly)
library(tidyquant)
library(readr)
```

## Make sure to run format_Demographic before 

#supplentary Table 2
```{r, message=FALSE,warning=FALSE, echo = FALSE}
#select out participants who only completed prescreen
Just_Prescreen_Dem= filter(Part_Dem_age_bmi, Phone_Screen == "No" & Prescreen_Survey == "Yes")
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#age grouping for prescreen only group
vtree(Just_Prescreen_Dem, "Prescreen_Survey Age_grouping", palette = 3, sortfill = TRUE, horiz=FALSE)
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#BMI for prescreen only participants
vtree(Just_Prescreen_Dem, "Prescreen_Survey BMI_Type", palette = 3, sortfill = TRUE, horiz=FALSE)
```


# Table 1
```{r, message=FALSE,warning=FALSE, echo = FALSE}
#select out participants who only completed phone screen
Just_Phone_Screen_Dem= filter(Part_Dem_age_bmi, Prescreen_Survey == "No")
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#age grouping for phone screen only group
vtree(Just_Phone_Screen_Dem, "Phone_Screen Age_grouping", palette = 3, sortfill = TRUE, horiz=FALSE)
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#BMI for phone screen only group
vtree(Just_Phone_Screen_Dem, "Phone_Screen BMI", palette = 3, sortfill = TRUE, horiz=FALSE)
```

# Both Phonscreening and Prescreen
```{r, message=FALSE,warning=FALSE, echo = FALSE}
#sort by participants who completed both phonescreen and prescreen
Combined_Dem= filter(Part_Dem_age_bmi, Phone_Screen == "Yes" & Prescreen_Survey == "Yes")
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#age grouping for combined participants
vtree(Combined_Dem, "Prescreen_Survey Phone_Screen Age_grouping", palette = 3, sortfill = TRUE, horiz=FALSE)
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#BMI for combined participants
vtree(Combined_Dem, "Prescreen_Survey Phone_Screen BMI", palette = 3, sortfill = TRUE, horiz=FALSE)
```

#anaylsis
#Age
```{r, message=FALSE,warning=FALSE, echo = FALSE}
Dem_Age = Part_Dem_age_bmi[Part_Dem_age_bmi$Encounter_Type != "Prescreen", ]  
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
Dem_Age = select(filter(Dem_Age),c(Encounter_Type,Age_grouping))
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
Dem_Age <- na.omit(Dem_Age) 
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
chisq.test(Dem_Age$Encounter_Type, Dem_Age$Age_grouping, correct=FALSE)
#X^2=5.1509
#p=0.1611
```
#BMI
```{r, message=FALSE,warning=FALSE, echo = FALSE}
Dem_BMI = Part_Dem_age_bmi[Part_Dem_age_bmi$Encounter_Type != "Prescreen", ]  
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
Dem_BMI = select(filter(Dem_BMI),c(Encounter_Type,BMI))
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
Dem_BMI <- na.omit(Dem_BMI) 
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
chisq.test(Dem_BMI$Encounter_Type, Dem_BMI$BMI, correct=FALSE)
#X^2=6.2554
#p=0.04382
```
