---
title: "anaylze_DemographicPhases_Part2"
author: "Yasmine Gillespie"
date: "2023-06-02"
output: html_document
---
```{r, include=FALSE}
##-------------- 
# **************************************************************************** #
# ***************                Project Overview              *************** #
# **************************************************************************** #
# Author:      Dominick Lemas
# Date:        Nov 17, 2020 
# Modify:      
# IRB:         UFHealth Early Life Exposures and Pediatric Outcomes (IRB201601899) 
# version: R version 4.0.2 (2020-06-22)
# version: Rstudio version Version 1.3.959 
# **************************************************************************** #
# ***************                Description                   *************** #
# **************************************************************************** #
# PLAN: Access redcap via API and pull/format/clean data for downstream analysis.
# Note: vpn must be active
# Next steps
#- function to call the IDs and events
#- function to batch pull EHR data by year/event and combine into final dataset. 
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
# **************************************************************************** #
# ***************                Library                       *************** #
# **************************************************************************** #
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
library(tidyverse)
library(dplyr)
library(flextable)
library(gt)
library(formattable)
library(gtsummary)
library(ggplot2)
library(ggrepel)
library(keyringr)
library(readxl)
library(redcapAPI)
library(REDCapR)
library(vtree)
library(vistime)
library(labelled)
library(plyr)
library(plotly)
library(tidyquant)
library(readr)
```

## Make sure run format_DemographicPart2

#supplmentary Table 2
```{r, message=FALSE,warning=FALSE, echo = FALSE}
Only_PreScreen_DEM= filter(PD_Gest, Phone_Screen == "No" )
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#pregnant for prescreen 
vtree(Only_PreScreen_DEM, "Prescreen_Survey Prego", palette = 3, sortfill = TRUE, horiz=FALSE)
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#delivery in GNV for prescreen
vtree(Only_PreScreen_DEM, "Prescreen_Survey GNV", palette = 3, sortfill = TRUE, horiz=FALSE)
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#mode of delivery for prescreen
vtree(Only_PreScreen_DEM, "Prescreen_Survey Mod", palette = 3, sortfill = TRUE, horiz=FALSE)
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#gestation weeks for prescreen survey
vtree(Only_PreScreen_DEM, "Prescreen_Survey gest_wks_groups", palette = 3, sortfill = TRUE, horiz=FALSE)
```


#Table 1
```{r, message=FALSE,warning=FALSE, echo = FALSE}
#filter for only phone screen
Only_Phone_Screen_DEM= filter(PD_Gest, Prescreen_Survey == "No")
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#pregnant for phone screen participants
#change NA to missing so it is accounted for in vtree
mod_vtree <- Only_Phone_Screen_DEM
mod_vtree$`Prego`[is.na(mod_vtree$`Prego`)] <- "Missing"

vtree(mod_vtree, "Phone_Screen Prego", palette = 3, sortfill = TRUE, horiz = FALSE, showpct = TRUE)

#vtree(Only_Phone_Screen_DEM, "Phone_Screen Prego", palette = 3, sortfill = TRUE, horiz=FALSE)
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#delivery in GNV for phone screen participants
#change NA to missing so it is accounted for in vtree
mod_vtree <- Only_Phone_Screen_DEM
mod_vtree$`GNV`[is.na(mod_vtree$`GNV`)] <- "Missing"

vtree(mod_vtree, "Phone_Screen GNV", palette = 3, sortfill = TRUE, horiz = FALSE, showpct = TRUE)

#vtree(Only_Phone_Screen_DEM, "Phone_Screen GNV", palette = 3, sortfill = TRUE, horiz=FALSE)
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#mode of delivery for phone screen
#change NA to missing so it is accounted for in vtree
mod_vtree <- Only_Phone_Screen_DEM
mod_vtree$`Mod`[is.na(mod_vtree$`Mod`)] <- "Missing"

vtree(mod_vtree, "Phone_Screen Mod", palette = 3, sortfill = TRUE, horiz = FALSE, showpct = TRUE)
#vtree(Only_Phone_Screen_DEM, "Phone_Screen Mod", palette = 3, sortfill = TRUE, horiz=FALSE)
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#gestation weeks for phone screen participants
#change NA to missing so it is accounted for in vtree
mod_vtree <- Only_Phone_Screen_DEM
mod_vtree$`gest_wks_groups`[is.na(mod_vtree$`gest_wks_groups`)] <- "Missing"

vtree(mod_vtree, "Phone_Screen gest_wks_groups", palette = 3, sortfill = TRUE, horiz = FALSE, showpct = TRUE)
#vtree(Only_Phone_Screen_DEM, "Phone_Screen gest_wks_groups", palette = 3, sortfill = TRUE, horiz=FALSE)
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#participants who completed both prescreen and phone screen
Both_DEM= filter(PD_Gest, Phone_Screen == "Yes" & Prescreen_Survey == "Yes")
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#pregnant for both
mod_vtree <- Both_DEM
mod_vtree$`Prego`[is.na(mod_vtree$`Prego`)] <- "Missing"

vtree(mod_vtree, "Phone_Screen Prego", palette = 3, sortfill = TRUE, horiz = FALSE, showpct = TRUE)
#vtree(Both_DEM, "Prescreen_Survey Phone_Screen Prego", palette = 3, sortfill = TRUE, horiz=FALSE)
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#delivery in GNV for both
mod_vtree <- Both_DEM
mod_vtree$`GNV`[is.na(mod_vtree$`GNV`)] <- "Missing"

vtree(mod_vtree, "Phone_Screen GNV", palette = 3, sortfill = TRUE, horiz = FALSE, showpct = TRUE)
#vtree(Both_DEM, "Prescreen_Survey Phone_Screen GNV", palette = 3, sortfill = TRUE, horiz=FALSE)
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#mode of delivery for both
mod_vtree <- Both_DEM
mod_vtree$`Mod`[is.na(mod_vtree$`Mod`)] <- "Missing"

vtree(mod_vtree, "Phone_Screen Mod", palette = 3, sortfill = TRUE, horiz = FALSE, showpct = TRUE)
#vtree(Both_DEM, "Prescreen_Survey Phone_Screen Mod", palette = 3, sortfill = TRUE, horiz=FALSE)
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#gestation weeks for both
mod_vtree <- Both_DEM
mod_vtree$`gest_wks_groups`[is.na(mod_vtree$`gest_wks_groups`)] <- "Missing"

vtree(mod_vtree, "Phone_Screen gest_wks_groups", palette = 3, sortfill = TRUE, horiz = FALSE, showpct = TRUE)
#vtree(Both_DEM, "Prescreen_Survey Phone_Screen gest_wks_groups", palette = 3, sortfill = TRUE, horiz=FALSE)
```

#anaylsis
#Prego
```{r, message=FALSE,warning=FALSE, echo = FALSE}
Dem_prego = PD_Gest[PD_Gest$Encounter_Type != "Prescreen", ]  
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
Dem_prego = select(filter(Dem_prego),c(Encounter_Type,Prego))
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
Dem_prego <- na.omit(Dem_prego) 
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
chisq.test(Dem_prego$Encounter_Type, Dem_prego$Prego, correct=FALSE)
#X^2=3.0967
#p=0.07845
```
#GNV
```{r, message=FALSE,warning=FALSE, echo = FALSE}
Dem_GNV = PD_Gest[PD_Gest$Encounter_Type != "Prescreen", ]  
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
Dem_GNV = select(filter(Dem_GNV),c(Encounter_Type,GNV))
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
Dem_GNV <- na.omit(Dem_GNV) 
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
chisq.test(Dem_GNV$Encounter_Type, Dem_GNV$GNV, correct=FALSE)
#X^2=0.39677
#p=0.5288
```
#Mod
```{r, message=FALSE,warning=FALSE, echo = FALSE}
Dem_Mod = PD_Gest[PD_Gest$Encounter_Type != "Prescreen", ]  
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
Dem_Mod = select(filter(Dem_Mod),c(Encounter_Type,Mod))
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
Dem_Mod <- na.omit(Dem_Mod) 
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
chisq.test(Dem_Mod$Encounter_Type, Dem_Mod$Mod, correct=FALSE)
#X^2=9.2862e-05
#p=0.9923
```

#Gestation Weeks
```{r, message=FALSE,warning=FALSE, echo = FALSE}
Dem_Gest = PD_Gest[PD_Gest$Encounter_Type != "Prescreen", ]  
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
Dem_Gest = select(filter(Dem_Gest),c(Encounter_Type,gest_wks_groups))
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
Dem_Gest <- na.omit(Dem_Gest) 
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
chisq.test(Dem_Gest$Encounter_Type, Dem_Gest$gest_wks_groups, correct=FALSE)
#X^2=1.7063
#p=0.6355
```