---
title: "build_RecruitmentOutcomes_Barplot"
author: "Yasmine Gillespie"
date: "2023-06-02"
output: html_document
editor_options: 
  chunk_output_type: inline
---

# run getData_Current_Participant and anaylze_Current_Participant_table1 before

```{r, include=FALSE}
##-------------- 
# **************************************************************************** #
# ***************                Project Overview              *************** #
# **************************************************************************** #
# Author:      Dominick Lemas
# Date:        Nov 17, 2020 
# Modify:      
# IRB:         UFHealth Early Life Exposures and Pediatric Outcomes (IRB201601899) 
# version: R version 4.0.2 (2020-06-22)
# version: Rstudio version Version 1.3.959 
# **************************************************************************** #
# ***************                Description                   *************** #
# **************************************************************************** #
# PLAN: Access redcap via API and pull/format/clean data for downstream analysis.
# Note: vpn must be active
# Next steps
#- function to call the IDs and events
#- function to batch pull EHR data by year/event and combine into final dataset. 
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
# **************************************************************************** #
# ***************                Library                       *************** #
# **************************************************************************** #
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
library(tidyverse)
library(dplyr)
library(flextable)
library(gt)
library(formattable)
library(gtsummary)
library(ggplot2)
library(ggrepel)
library(keyringr)
library(readxl)
library(redcapAPI)
library(REDCapR)
library(vtree)
library(vistime)
library(labelled)
library(plyr)
library(plotly)
library(tidyquant)
library(readr)
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
Phone_Screen_age_bmi = Phone_Screen_age_bmi %>%
  select(test_id, Recruitment, Consent, Complete, beachphone_pass_fail)

###making data frame for barplot
PS_Consented <- Phone_Screen_age_bmi[Phone_Screen_age_bmi$Consent=="Yes",]
barplot_consent = (table(PS_Consented$Recruitment))
PS_Eligible <- Phone_Screen_age_bmi[Phone_Screen_age_bmi$beachphone_pass_fail=="Pass",]
PS_Eligible <- na.omit(PS_Eligible)
PS_Eligible <- PS_Eligible[!PS_Eligible$Recruitment=="Incomplete",]
barplot_eligible = (table(PS_Eligible$Recruitment))
PS_Completed<- Phone_Screen_age_bmi[Phone_Screen_age_bmi$Complete=="Yes",]
barplot_completed = (table(PS_Completed$Recruitment))
#counting values
data <- data.frame(barplot_eligible,barplot_consent,barplot_completed)
names(data)[1] <- "Recruitment"
names(data)[2] <- "Eligible"
names(data)[4] <- "Consent"
names(data)[6] <- "Complete"
data <- data[ -c(3,5) ]
#changing column titles, cutting out extra recruitment type column
data <- as.data.frame(t(data))
names(data) <- data[1,]
data <- data[-1,]
#switching column and row
data$`Flyer` <- as.numeric(data$`Flyer` )
data$ `Other` <- as.numeric(data$ `Other`)
data$`Facebook` <- as.numeric(data$`Facebook`)
data$`Word-of-mouth` <- as.numeric(data$`Word-of-mouth`)
#changing variables in data frame to be numeric instead of character
data1 <- as.matrix(data)
#making matrix to plug into barplot
x11()
library(graphics)
#run for graphics to work correctly
```

```{r echo=, message=FALSE, warning=FALSE}
###barplot
#open png device to save
png("RecruitmentOutcomes_barplotA.png", width = 1000, height = 600)

bar_heights <- barplot( data1,beside=TRUE, col = c("blue","orange", "black"), ylab = "Counts", ylim = c(0,70), legend.text = TRUE, cex.axis = 1.5, cex.lab = 1.5, cex.names = 1.5)

# Create the legend title and labels
legend_title <- "Enrollment Outcome"
legend_labels <- c("Eligible", "Consented", "Completed")

# Add the legend with the title and labels
legend("topright", legend = legend_labels, fill = c("blue","orange", "black"),
       title = legend_title, cex = 2)

#add counts to the barplot
bar_heights <- barplot(data1, beside = TRUE, col = c("blue","orange", "black"),
                       xlab = "Recruitment Method", ylab = "Counts", ylim = c(0, 60), 
                       legend.text = TRUE, plot = FALSE)
text(x = bar_heights, y = data1, label = data1, pos = 3, cex = 1.5, col = "black")

# Close the PNG device
dev.off()

```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#convert to percentages
`Consented` <- round((data1[2, ] / data1[1, ])*100, digits = 0)
data2 <- rbind(data1, `Consented`)
`Completed` <- round((data1[3, ] / data1[2, ])*100, digits = 0)
data3 <- rbind(data2, `Completed`)

#delete rows 
data3  <- data3 [-c(1, 2,3), ]

```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
###barplot
png("RecruitmentOutcomes_barplotB.png", width = 1000, height = 600)


bar_heights <- barplot( data3,beside=TRUE, col = c("blue","orange"), ylab = "Percentage", ylim = c(0,120), xlab = "Enrollment", legend.text = TRUE, cex.axis = 1.5, cex.lab = 1.5, cex.names = 1.5)

#add % to the percentages
percentages <- paste0(round(data3), "%")

#add percentages to barplot
text(x = bar_heights, y = data3, labels = percentages, pos = 3, cex = 1.5)

# Create the legend title and labels
legend_title <- "Enrollment Outcome"
legend_labels <- c("Consented", "Completed")

# Add the legend with the title and labels
legend("topright", legend = legend_labels, fill = c("blue","orange"),
       title = legend_title, cex = 2)

# Close the PNG device
dev.off()

```
