---
title: "BEACH study BMI recruitment overtime"
author: "Yasmine Gillespie, Michele Himadi"
date: "2024-06-05"
output: html_document
---

```{r, include=FALSE,echo=FALSE}
##-------------- 
# **************************************************************************** #
# ***************                Project Overview              *************** #
# **************************************************************************** #

# Author:      Yasmine Gillespie, Michele Himadi
# Date:        Oct 25, 2022 
# Modify:      June 5, 2024
# IRB:         UFHealth Early Life Exposures and Pediatric Outcomes (IRB201601899) 

# version: R version 4.2.2 (2022-10-31)
# version: Rstudio version Version 1.3.959 

# **************************************************************************** #
# ***************                Description                   *************** #
# **************************************************************************** #

# PLAN: Access redcap via API and pull/format/clean data for downstream analysis.
# Note: vpn must be active

```

```{r, message=FALSE,warning=FALSE, echo = FALSE}

# **************************************************************************** #
# ***************                Library                       *************** #
# **************************************************************************** #

knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
library(tidyverse)
library(dplyr)
library(flextable)
library(gt)
library(formattable)
library(gtsummary)
library(ggplot2)
library(ggrepel)
library(keyringr)
library(readxl)
library(redcapAPI)
library(REDCapR)
library(vtree)
library(vistime)
library(labelled)
library(plyr)
library(plotly)
library(tidyquant)
library(readr)


library(scales)
library(viridis)
library(ggthemes)
library(gridExtra)
library(lubridate)
library(data.table)

library(tidyquant)
library(ggplot2)
library(plyr)
library(plotly)
library(stringi)
library(anytime)
library(ggpattern)

# Load libraries
```


```{r, message=FALSE,include=FALSE}

# **************************************************************************** #
# ***************              Load Data                       *************** #
# ****************************************************************************#

load("~/BEACH-Reports/output/reports/recruitment/BMI_barplot.RData")

```

```{r, message=FALSE,warning=FALSE,echo=FALSE}
#make bmi waffle

BMI_barplot=BMI_barplot %>%
  mutate(bmi_group=recode(bmi_group,
                              "Normal"="NW",
                              "Overweight"="OWOB",
                              "Obese"= "OWOB"
                               ))

BMI_barplot_clean = BMI_barplot %>% select(test_id, timecoalesce, bmi_group)
BMI_barplot_clean = na.omit(BMI_barplot_clean)

BMI_NW = filter(BMI_barplot_clean, bmi_group == "NW")
BMI_OWOB = filter(BMI_barplot_clean, bmi_group != "NW")

BMI_NW$time = anydate(BMI_NW$timecoalesce)


BMI_OWOB$time = anydate(BMI_OWOB$timecoalesce)


```


```{r,message=FALSE,include=FALSE}
#counts for each quarter

NW_months <- BMI_NW[4]
NW_months$month<-factor(month(NW_months$time),levels=as.character(1:12),labels=c("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec")) 
OWOB_months <- BMI_OWOB[4]
OWOB_months$month<-factor(month(OWOB_months$time),levels=as.character(1:12),labels=c("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec")) 

OWOB_months <- na.omit(OWOB_months)

#normal weight
sum(NW_months$month == 'Jan' | NW_months$month == 'Feb' | NW_months$month == 'Mar')
sum(NW_months$month == 'Apr' | NW_months$month == 'May' | NW_months$month == 'Jun')
sum(NW_months$month == 'Jul' | NW_months$month == 'Aug' | NW_months$month == 'Sep')
sum(NW_months$month == 'Oct' | NW_months$month == 'Nov' | NW_months$month == 'Dec')

#overweight/obese
sum(OWOB_months$month == 'Jan' | OWOB_months$month == 'Feb' | OWOB_months$month == 'Mar')
sum(OWOB_months$month == 'Apr' | OWOB_months$month == 'May' | OWOB_months$month == 'Jun')
sum(OWOB_months$month == 'Jul' | OWOB_months$month == 'Aug' | OWOB_months$month == 'Sep')
sum(OWOB_months$month == 'Oct' | OWOB_months$month == 'Nov' | OWOB_months$month == 'Dec')

```


#bar plot based on waffle plot months

```{r,message=FALSE,include=FALSE}
#make data frames
BMI_bar <- BMI_barplot_clean[3]
BMI_bar[2] <- BMI_barplot_clean[2]
BMI_bar$time <- anydate(BMI_barplot_clean$timecoalesce)
BMI_bar$month<-factor(month(BMI_bar$time),levels=as.character(1:12),labels=c("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"),ordered=TRUE) # finding the month
BMI_bar = BMI_bar %>%
  select(bmi_group, month)

#creating counted data for each BMI and month
BMI_bar_counted <- count(BMI_bar)
BMI_bar_counted <- na.omit(BMI_bar_counted)
BMI_bar_counted=BMI_bar_counted %>%
  mutate(bmi_group=recode(bmi_group,
                              "NW"="Normal",
                              "OWOB"="Obese/Overweight"
                               ))


b <- ggplot(BMI_bar_counted, aes(x = month, y = freq, fill = bmi_group)) + geom_bar(stat = "identity", position = "dodge") + ylim(0,170) + geom_text(aes(label = freq), vjust = -1, position = position_dodge(width = 0.9)) + theme_light() + xlab("Month") + ylab("Counts") + guides(fill = guide_legend(title = "Obesity Status")) + theme(legend.title = element_text(size = 12), legend.text= element_text(size=12), text = element_text(size = 14)) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())

b

ggsave(b, filename = "BMI_barplot.png",height = 3, width = 10)
#save to computer to adjust size appropriately. adjust filename to where you want it saved


#adjust location of counts on barplot

```
