---
title: "BEACH Data: Participant Overview Report"
author: "Dominick Lemas"
date: "07/19/2022"
output: html_document

---

```{r, include=FALSE}
##-------------- 
# **************************************************************************** #
# ***************                Project Overview              *************** #
# **************************************************************************** #

# Author:            Dominick Lemas
# Start Date:        Nov 17, 2021 
# Date Modify:       
# IRB:               
#                   
#
# version: R version 4.0.2 (2020-06-22)
# version: Rstudio version Version 1.3.959 

# **************************************************************************** #
# ***************                Description                   *************** #
# **************************************************************************** #

# PLAN: Access redcap via API and pull/format/clean data for downstream analysis.
# Note: vpn must be active

# keyringr: https://cran.r-project.org/web/packages/keyringr/vignettes/Avoiding_plain_text_passwords_in_R_with_keyringr.html

```


```{r, message=FALSE}

# **************************************************************************** #
# ***************                Library                       *************** #
# **************************************************************************** #

library(keyringr)
library(redcapAPI)
library(REDCapR)
library(readxl)
library(tidyverse)
source("~/BEACH-reports/code/utils/utils.R")

```

```{r, message=FALSE}

# API & URL
#----------
uri <- "https://redcap.ctsi.ufl.edu/redcap/api/"
api_token=get_API_token("beach_api")

# REPORT IDS
#-----------

# Study Overview
report_id<-21221L

# PULL DATA
#-----------
report <-
  REDCapR::redcap_report(
    redcap_uri = uri,
    token      = api_token,
    report_id  = report_id
  )$data

```

```{r, message=FALSE}

# FORMAT DATA
#------------

data = report %>%
  select(-redcap_event_name,-redcap_repeat_instrument,-redcap_repeat_instance,    # drop out variables not needed
         -clinical_health_update_2wk_v4_042218_complete,
         -health_update_3rd_trimester_v5082518_complete,-biosample_notes,
         -infant_postnatal_care_other,-mom_healthcare_other,
         -exitsurvey_resultsinfo) %>% 
  gather("infant_race", "value", infant_race_nih___1:infant_race_nih___6) %>%
  filter(value==1) %>%
  mutate(infant_race=recode_factor(infant_race,
                                     "infant_race_nih___1" = "NativeAmerican", 
                                     "infant_race_nih___2" = "Asian", 
                                     "infant_race_nih___3" = "Black", 
                                     "infant_race_nih___4" = "PacificIsland", 
                                     "infant_race_nih___5" = "White",
                                     "infant_race_nih___6" = "NA")) %>%
  select(-value) %>%
  gather("encounter_type", "value", encounter_type___1:encounter_type___6) %>%
  filter(value==1) %>%
  mutate(encounter_type=recode_factor(encounter_type,
                                     "encounter_type___1" = "random contact", 
                                     "encounter_type___2" = "pre-screen survey", 
                                     "encounter_type___3" = "phone screen", 
                                     "encounter_type___4" = "IDR", 
                                     "encounter_type___5" = "consent",
                                     "encounter_type___6" = "complete")) %>%
  select(-value) %>%
  gather("biosample_visits", "value", biosample_visits___1 :biosample_visits___5) %>%
  filter(value==1) %>%
  mutate(biosample_visits=recode_factor(biosample_visits,
                                     "biosample_visits___1" = "3rd-tri", 
                                     "biosample_visits___2" = "2-wk", 
                                     "biosample_visits___3" = "2-mo", 
                                     "biosample_visits___4" = "6-mo", 
                                     "biosample_visits___5" = "12-mo")) %>%
  select(-value)

```
