---
title: "Recruitment outcomes of individuals screened for eligibility according to recruitment channels and BMI"
author: "Michele Himadi"
date: "2024-06-10"
output: html_document
---

```{r, include=FALSE}
##-------------- 
# **************************************************************************** #
# ***************                Project Overview              *************** #
# **************************************************************************** #
# Author:      Dominick Lemas, Michele Himadi
# Date:        Nov 17, 2020 
# Modify:      June 10, 2024
# IRB:         UFHealth Early Life Exposures and Pediatric Outcomes (IRB201601899) 
# version: R version 4.0.2 (2020-06-22)
# version: Rstudio version Version 1.3.959 
# **************************************************************************** #
# ***************                Description                   *************** #
# **************************************************************************** #
# PLAN: Access redcap via API and pull/format/clean data for downstream analysis.
# Note: vpn must be active
# Next steps
#- function to call the IDs and events
#- function to batch pull EHR data by year/event and combine into final dataset. 
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
# **************************************************************************** #
# ***************                Library                       *************** #
# **************************************************************************** #
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
library(tidyverse)
library(dplyr)
library(flextable)
library(gt)
library(formattable)
library(gtsummary)
library(ggplot2)
library(ggrepel)
library(keyringr)
library(readxl)
library(redcapAPI)
library(REDCapR)
library(vtree)
library(vistime)
library(labelled)
library(plyr)
library(plotly)
library(tidyquant)
library(readr)
library(stats)
```

#Recruitment outcomes of individuals screened for eligibility according to recruitment channels and BMI
```{r, message=FALSE,warning=FALSE, echo = FALSE}
BMI_outcomes <- Phone_Screen_age_bmi %>% select(Recruitment, BMI, Outcomes) %>% na.omit() %>% filter(!str_detect(Recruitment, "Incomplete")) 
BMI_outcomes <- filter(BMI_outcomes, !(BMI == "Underweight" | BMI == "Overweight"))

#numbers for BMI outcomes
vtree(BMI_outcomes, "Recruitment BMI Outcomes", palette=3, sortfill=TRUE, horiz=TRUE)

#breaking them down into smaller chunks to be more readable
BMI_outcomes_Facebook <- BMI_outcomes %>% select(Recruitment, BMI, Outcomes) %>% na.omit() %>% filter(str_detect(Recruitment, "Facebook"))
vtree(BMI_outcomes_Facebook, "BMI Outcomes", palette=3, sortfill=TRUE, horiz=TRUE)

BMI_outcomes_Flyer <- BMI_outcomes %>% select(Recruitment, BMI, Outcomes) %>% na.omit() %>% filter(str_detect(Recruitment, "Flyer"))
vtree(BMI_outcomes_Flyer, "BMI Outcomes", palette=3, sortfill=TRUE, horiz=TRUE)

BMI_outcomes_Wom <- BMI_outcomes %>% select(Recruitment, BMI, Outcomes) %>% na.omit() %>% filter(str_detect(Recruitment, "Word-of-mouth"))
vtree(BMI_outcomes_Wom, "BMI Outcomes", palette=3, sortfill=TRUE, horiz=TRUE)

BMI_outcomes_Other <- BMI_outcomes %>% select(Recruitment, BMI, Outcomes) %>% na.omit() %>% filter(str_detect(Recruitment, "Other"))
vtree(BMI_outcomes_Other, "BMI Outcomes", palette=3, sortfill=TRUE, horiz=TRUE)

#analysis for X^2 and p value
x <- BMI_outcomes$Recruitment # First categorical variable
y <- BMI_outcomes$BMI  # Second categorical variable
z <- BMI_outcomes$Outcomes # Third categorical variable

# Create a contingency table
table_data <- table(x, y, z)

# Perform CMH test
result <- mantelhaen.test(table_data )

# Print the result
print(result)
#M^2 = 4.6383
#p-value = 0.2003

```
