---
title: "anaylze_Recruitment_BMI_Type"
author: "Yasmine Gillespie"
date: "2023-06-02"
output: html_document
---

```{r, include=FALSE}
##-------------- 
# **************************************************************************** #
# ***************                Project Overview              *************** #
# **************************************************************************** #
# Author:      Dominick Lemas
# Date:        Nov 17, 2020 
# Modify:      
# IRB:         UFHealth Early Life Exposures and Pediatric Outcomes (IRB201601899) 
# version: R version 4.0.2 (2020-06-22)
# version: Rstudio version Version 1.3.959 
# **************************************************************************** #
# ***************                Description                   *************** #
# **************************************************************************** #
# PLAN: Access redcap via API and pull/format/clean data for downstream analysis.
# Note: vpn must be active
# Next steps
#- function to call the IDs and events
#- function to batch pull EHR data by year/event and combine into final dataset. 
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
# **************************************************************************** #
# ***************                Library                       *************** #
# **************************************************************************** #
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
library(tidyverse)
library(dplyr)
library(flextable)
library(gt)
library(formattable)
library(gtsummary)
library(ggplot2)
library(ggrepel)
library(keyringr)
library(readxl)
library(redcapAPI)
library(REDCapR)
library(vtree)
library(vistime)
library(labelled)
library(plyr)
library(plotly)
library(tidyquant)
library(readr)
library(stats)
```


#BMI_type vs Recruitment vs Outcomes 
#Total outcomes 
```{r, message=FALSE,warning=FALSE, echo = FALSE}
#Omiting incomplete Recruitment types
Recruitment_Type = Phone_Screen_age_bmi[Phone_Screen_age_bmi$Recruitment != "Incomplete", ]  
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
BMI_Type_Outcomes = select(filter(Recruitment_Type),c(Recruitment, BMI, Outcomes))
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
BMI_Type_Outcomes  <- na.omit(BMI_Type_Outcomes ) 
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
# Sample data
x <- BMI_Type_Outcomes$Recruitment # First categorical variable
y <- BMI_Type_Outcomes$BMI  # Second categorical variable
z <- BMI_Type_Outcomes$Outcomes # Third categorical variable

# Create a contingency table
table_data <- table(x, y, z)

# Perform CMH test
result <- mantelhaen.test(table_data )

# Print the result
print(result)

#M^2: 5.506
#p-value: 0.4807


```

##analysis from deleted table
#Eligible 
```{r, message=FALSE,warning=FALSE, echo = FALSE}
BMI_Type_Eligible = select(filter(Recruitment_Type),c(Recruitment, BMI, beachphone_pass_fail))
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
BMI_Type_Eligible = BMI_Type_Eligible[BMI_Type_Eligible$beachphone_pass_fail != "Incomplete", ]  
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
BMI_Type_Eligible  <- na.omit(BMI_Type_Eligible  ) 
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
# Sample data
x <- BMI_Type_Eligible$Recruitment # First categorical variable
y <- BMI_Type_Eligible$BMI  # Second categorical variable
z <- BMI_Type_Eligible$beachphone_pass_fail # Third categorical variable

# Create a contingency table
table_data <- table(x, y, z)

# Perform CMH test
result <- mantelhaen.test(table_data )

# Print the result
print(result)

#M^2: 6.3917
#p-value: 0.3808

```

#Consent 
```{r, message=FALSE,warning=FALSE, echo = FALSE}
BMI_Type_Consent = select(filter(Recruitment_Type),c(Recruitment, BMI, Consent))
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
BMI_Type_Consent  <- na.omit(BMI_Type_Consent  ) 
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
# Sample data
x <- BMI_Type_Consent$Recruitment # First categorical variable
y <- BMI_Type_Consent$BMI  # Second categorical variable
z <- BMI_Type_Consent$Consent # Third categorical variable

# Create a contingency table
table_data <- table(x, y, z)

# Perform CMH test
result <- mantelhaen.test(table_data )

# Print the result
print(result)

#M^2: 6.0138
#p-value: 0.4216

```

#Complete
```{r, message=FALSE,warning=FALSE, echo = FALSE}
BMI_Type_Complete = select(filter(Recruitment_Type),c(Recruitment, BMI, Complete))
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
BMI_Type_Complete  <- na.omit(BMI_Type_Complete  ) 
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
# Sample data
x <- BMI_Type_Complete$Recruitment # First categorical variable
y <- BMI_Type_Complete$BMI  # Second categorical variable
z <- BMI_Type_Complete$Complete # Third categorical variable

# Create a contingency table
table_data <- table(x, y, z)

# Perform CMH test
result <- mantelhaen.test(table_data )

# Print the result
print(result)

#M^2: 6.0259
#p-value: 0.4203

```


#Table 3 BMI vs Outcomes 
```{r, message=FALSE,warning=FALSE, echo = FALSE}
#pregnant for both
vtree(Phone_Screen_age_bmi, "BMI beachphone_pass_fail Consent Complete", palette = 3, sortfill = TRUE, horiz=FALSE)

#table 3 n=212
vtree_plot <- vtree(BMI_Type_Outcomes, "Recruitment BMI Outcomes", sortfill = TRUE)
saveWidget(vtree_plot, "vtree_plot.html")

```

#Total Outcomes anaylsis
```{r, message=FALSE,warning=FALSE, echo = FALSE}
BMI_Type = Phone_Screen_age_bmi[Phone_Screen_age_bmi$Recruitment != "Incomplete", ]  
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
BMI_Type_Outcomes_2 = select(filter(BMI_Type),c( BMI, Outcomes))
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
BMI_Type_Outcomes_2  <- na.omit(BMI_Type_Outcomes_2 ) 
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
chisq.test(BMI_Type_Outcomes_2$BMI, BMI_Type_Outcomes_2$Outcomes)
#X^2=8.9288
#p=0.03025
```



