---
title: "Recruitment outcomes based on obesity status and recruitment method"
author: "Yasmine Gillespie, Michele Himadi"
date: "2024-06-05"
output: html_document
---
```{r, include=FALSE}
##-------------- 
# **************************************************************************** #
# ***************                Project Overview              *************** #
# **************************************************************************** #
# Author:      Yasmine Gillespie, Michele Himadi
# Date:        Nov 17, 2020 
# Modify:      June 5, 2024
# IRB:         UFHealth Early Life Exposures and Pediatric Outcomes (IRB201601899) 
# version: R version 4.0.2 (2020-06-22)
# version: Rstudio version Version 1.3.959 
# **************************************************************************** #
# ***************                Description                   *************** #
# **************************************************************************** #
# PLAN: Access redcap via API and pull/format/clean data for downstream analysis.
# Note: vpn must be active
# Next steps
#- function to call the IDs and events
#- function to batch pull EHR data by year/event and combine into final dataset. 
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
# **************************************************************************** #
# ***************                Library                       *************** #
# **************************************************************************** #
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
library(tidyverse)
library(dplyr)
library(flextable)
library(gt)
library(formattable)
library(gtsummary)
library(ggplot2)
library(ggrepel)
library(keyringr)
library(readxl)
library(redcapAPI)
library(REDCapR)
library(vtree)
library(vistime)
library(labelled)
library(plyr)
library(plotly)
library(tidyquant)
library(readr)
```

#Overweight +Obese

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#remove age grouping
BMI_outcomes = Phone_Screen_age_bmi %>%
  select(-Age_grouping) %>%
  filter(BMI_Type == "Normal" | BMI_Type == "Obese")

BMI_outcomes$Normal_Weight<- ifelse(BMI_outcomes$BMI=="Normal", "Yes", "No")
BMI_outcomes$OB<- ifelse(BMI_outcomes$BMI=="Obese", "Yes", "No")


```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#filter for participants who completed phone screen
BMI_outcomes= filter(BMI_outcomes, beachphone_pass_fail == "Pass")
BMI_outcomes = filter(BMI_outcomes, Recruitment != "Incomplete")
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
###making data frame for barplot

PS_BMI_NW <- BMI_outcomes[BMI_outcomes$Normal_Weight=="Yes",]
PS_BMI_NW<- na.omit(PS_BMI_NW)
barplot_BMI_NW = (table(PS_BMI_NW$Recruitment))
PS_BMI_OB <- BMI_outcomes[BMI_outcomes$OB=="Yes",]
PS_BMI_OB<- na.omit(PS_BMI_OB)
barplot_BMI_OB = (table(PS_BMI_OB$Recruitment))
#counting values
data <- data.frame(barplot_BMI_NW, barplot_BMI_OB)
names(data)[1] <- "Recruitment"
names(data)[2] <- "Normal Weight"
names(data)[4] <- "Obese"
data <- data[ -c(3) ]
#changing column titles, cutting out extra recruitment type column
data <- as.data.frame(t(data))
names(data) <- data[1,]
data <- data[-1,]
#switching column and row
data$`Flyer` <- as.numeric(data$`Flyer` )
data$ `Other` <- as.numeric(data$ `Other`)
data$`Facebook` <- as.numeric(data$`Facebook`)
data$`Word-of-mouth` <- as.numeric(data$`Word-of-mouth`)
#changing variables in data frame to be numeric instead of character
data1 <- as.matrix(data)
#making matrix to plug into barplot
x11()
library(graphics)
#run for graphics to work correctly
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
###barplot

#open png device to save
png("BMIoutcomes_barplotA.png", width = 1000, height = 600)

#create the barplot
barplot(data1, beside = TRUE, col = c("#F8766D", "#00BFC4"), 
        xlab = "Recruitment Method", ylab = "Counts", ylim = c(0, 40), cex.axis = 1.5, cex.lab = 1.5, cex.names = 1.5,
        legend.text = TRUE)

legend_title <- "Obesity Status"
legend_labels <- c("Normal Weight", "Obesity")
#legend
legend("topright", legend = legend_labels, fill = c("#F8766D", "#00BFC4"),
       title = legend_title, cex = 1.5)

#add counts to the barplot
bar_heights <- barplot(data1, beside = TRUE, col = c("#F8766D", "#00BFC4"),
                       xlab = "Recruitment Method", ylab = "Counts", ylim = c(0, 60), 
                       legend.text = TRUE, plot = FALSE)
text(x = bar_heights, y = data1, label = data1, pos = 3, cex = 1.5, col = "black")

# Close the PNG device
dev.off()
```

# BMI % Consented 
```{r, message=FALSE,warning=FALSE, echo = FALSE}
###making data frame for barplot

PS_Eligible_NW <- BMI_outcomes[BMI_outcomes$beachphone_pass_fail=="Pass" & BMI_outcomes$Normal_Weight=="Yes",]
PS_Eligible_NW <- na.omit(PS_Eligible_NW)
PS_Eligible_NW <- PS_Eligible_NW[!PS_Eligible_NW$Recruitment=="Incomplete",]
barplot_eligible_NW = (table(PS_Eligible_NW$Recruitment))

PS_Eligible_OB <- BMI_outcomes[BMI_outcomes$beachphone_pass_fail=="Pass" & BMI_outcomes$OB=="Yes",]
PS_Eligible_OB <- na.omit(PS_Eligible_OB)
PS_Eligible_OB <- PS_Eligible_OB[!PS_Eligible_OB$Recruitment=="Incomplete",]
barplot_eligible_OB = (table(PS_Eligible_OB$Recruitment))

PS_BMI_NW <- BMI_outcomes[BMI_outcomes$Normal_Weight=="Yes" & BMI_outcomes$Consent=="Yes",]
PS_BMI_NW<- na.omit(PS_BMI_NW)
barplot_BMI_NW = (table(PS_BMI_NW$Recruitment))
PS_BMI_OB <- BMI_outcomes[BMI_outcomes$OB=="Yes" & BMI_outcomes$Consent=="Yes",]
PS_BMI_OB<- na.omit(PS_BMI_OB)
barplot_BMI_OB = (table(PS_BMI_OB$Recruitment))
#counting values
data <- data.frame(barplot_eligible_NW,barplot_BMI_NW,barplot_eligible_OB,barplot_BMI_OB)
names(data)[1] <- "Recruitment"
names(data)[2] <- "Eligible NW"
names(data)[4] <- "Normal Weight"
names(data)[6] <- "Eligible OB"
names(data)[8] <- "Obese/Overweight"
data <- data[ -c(3,5,7) ]
#changing column titles, cutting out extra recruitment type column
data <- as.data.frame(t(data))
names(data) <- data[1,]
data <- data[-1,]
#switching column and row
data$`Flyer` <- as.numeric(data$`Flyer` )
data$ `Other` <- as.numeric(data$ `Other`)
data$`Facebook` <- as.numeric(data$`Facebook`)
data$`Word-of-mouth` <- as.numeric(data$`Word-of-mouth`)
#changing variables in data frame to be numeric instead of character
data1 <- as.matrix(data)
#making matrix to plug into barplot
x11()
library(graphics)
#run for graphics to work correctly
```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#convert to percentages
`Consented_NW` <- round((data1[2, ] / data1[1, ])*100, digits = 0)
data2 <- rbind(data1, `Consented_NW`)
`Consented_OB` <- round((data1[4, ] / data1[3, ])*100, digits = 0)
data2 <- rbind(data2, `Consented_OB`)
#`Completed` <- round((data1[3, ] / data1[2, ])*100, digits = 0)
#data3 <- rbind(data2, `Completed`)

#delete rows 
data3  <- data2 [-c(1, 2,3,4), ]
rownames(data3)[1] <- "Normal Weight"
rownames(data3)[2] <- "Obesity"

```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
###barplot

#open png device to save
png("BMIOutcomes_barplotB.png", width = 1000, height = 600)

#create barplot
bar_heights <- barplot(data3, beside = TRUE, col = c("#F8766D", "#00BFC4"), 
                       ylab = "Percent Consented", ylim = c(0, 120), 
                       xlab = "Recruitment Method", legend.text = TRUE, cex.axis = 1.5, cex.lab = 1.5, cex.names = 1.5)

#adjust text positions
text_y_pos <- ifelse(data3 < 100, data3 + 5, 105)  # Adjusted logic for positioning

#add % to the percentages
percentages <- paste0(round(data3), "%")

#add percentages to barplot
text(x = bar_heights, y = text_y_pos, labels = percentages, pos = 3, cex = 1.5)

#legend and title
legend_title <- "Obesity Status"
legend_labels <- c("Normal Weight", "Obesity")
legend("topright", legend = legend_labels, fill = c("#F8766D", "#00BFC4"),
       title = legend_title, cex = 1.5)

# Close the PNG device
dev.off()

```


# BMI % Completed 
```{r, message=FALSE,warning=FALSE, echo = FALSE}
###making data frame for barplot

PS_BMI_NW <- BMI_outcomes[BMI_outcomes$Normal_Weight=="Yes" & BMI_outcomes$Consent=="Yes",]
PS_BMI_NW<- na.omit(PS_BMI_NW)
barplot_BMI_NW = (table(PS_BMI_NW$Recruitment))
PS_BMI_OB <- BMI_outcomes[BMI_outcomes$OB=="Yes" & BMI_outcomes$Consent=="Yes",]
PS_BMI_OB<- na.omit(PS_BMI_OB)
barplot_BMI_OB = (table(PS_BMI_OB$Recruitment))

PS_BMI_NW_Com <- BMI_outcomes[BMI_outcomes$Normal_Weight=="Yes" & BMI_outcomes$Complete=="Yes",]
PS_BMI_NW_Com<- na.omit(PS_BMI_NW_Com)
barplot_BMI_NW_Com = (table(PS_BMI_NW_Com$Recruitment))
PS_BMI_OB_Com <- BMI_outcomes[BMI_outcomes$OB=="Yes" & BMI_outcomes$Complete=="Yes",]
PS_BMI_OB_Com<- na.omit(PS_BMI_OB_Com)
barplot_BMI_OB_Com = (table(PS_BMI_OB_Com$Recruitment))

#counting values
data <- data.frame(barplot_BMI_NW_Com,barplot_BMI_NW,barplot_BMI_OB_Com,barplot_BMI_OB)
data  [is.na(data  )] <- 0
names(data)[1] <- "Recruitment"
names(data)[2] <- "Complete NW"
names(data)[4] <- "Consent NW"
names(data)[6] <- "Complete OB"
names(data)[8] <- "Consent OB"
data <- data[ -c(3,5,7) ]
#changing column titles, cutting out extra recruitment type column
data <- as.data.frame(t(data))
names(data) <- data[1,]
data <- data[-1,]
#switching column and row
data$`Flyer` <- as.numeric(data$`Flyer` )
data$ `Other` <- as.numeric(data$ `Other`)
data$`Facebook` <- as.numeric(data$`Facebook`)
data$`Word-of-mouth` <- as.numeric(data$`Word-of-mouth`)
#changing variables in data frame to be numeric instead of character
data1 <- as.matrix(data)
#making matrix to plug into barplot
x11()
library(graphics)
#run for graphics to work correctly


```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
#convert to percentages
`Complete_NW` <- round((data1[1, ] / data1[2, ])*100, digits = 0)
data2 <- rbind(data1, `Complete_NW`)
`Complete_OB` <- round((data1[3, ] / data1[4, ])*100, digits = 0)
data2 <- rbind(data2, `Complete_OB` )
#`Completed` <- round((data1[3, ] / data1[2, ])*100, digits = 0)
#data3 <- rbind(data2, `Completed`)

#delete rows 
data3  <- data2 [-c(1, 2,3,4), ]
rownames(data3)[1] <- "Normal Weight"
rownames(data3)[2] <- "Obesity"

```

```{r, message=FALSE,warning=FALSE, echo = FALSE}
###barplot
# Open PNG device to save
png("BMIOutcomes_barplotC.png", width = 1000, height = 600)

# Create the barplot and store the bar heights
bar_heights <- barplot(data3, beside = TRUE, col = c("#F8766D", "#00BFC4"), 
                       ylab = "Percent Completed", ylim = c(0, 150), 
                       xlab = "Recruitment Method", legend.text = TRUE, cex.axis = 1.5, cex.lab = 1.5,
                       cex.names = 1.5)  # Adjust size of x-axis labels

# Adjust text positions
text_y_pos <- ifelse(data3 < 100, data3 + 5, 105)  # Adjusted logic for positioning

# Add % to the percentages
percentages <- paste0(round(data3), "%")

# Add percentages to barplot
text(x = bar_heights, y = text_y_pos, labels = percentages, pos = 3, cex = 1.5)

# Legend and title
legend_title <- "Obesity Status"
legend_labels <- c("Normal Weight", "Obesity")
legend("topright", legend = legend_labels, fill = c("#F8766D", "#00BFC4"),
       title = legend_title, cex = 1.5)

# Close the PNG device
dev.off()

```