---
title: "Get RedCap Data: Diet Records Report"
author: "Dominick J. Lemas"
date: "10/11/2023"
output: html_document

---

```{r, include=FALSE}
##-------------- 
# **************************************************************************** #
# ***************                Project Overview              *************** #
# **************************************************************************** #

# Author:            Dominick J. Lemas
# Start Date:        04/15/2023 
# Date Modify:       
# Project:           The Breastfeeding and EArly Child Health Study
# IRB:               IRB201601034
#                   
#
# R version 4.3.1 (2023-06-16 ucrt) -- "Beagle Scouts"
# Copyright (C) 2023 The R Foundation for Statistical Computing
# Platform: x86_64-w64-mingw32/x64 (64-bit) 

# **************************************************************************** #
# ***************                Description                   *************** #
# **************************************************************************** #

# PLAN: Access redcap via API and fetch/format/ready data for downstream analysis.
# Note: vpn must be active

# keyringr must be installed: https://cran.r-project.org/web/packages/keyringr/vignettes/Avoiding_plain_text_passwords_in_R_with_keyringr.html

project_name="The Breastfeeding and EArly Child Health Study"
irb_number="IRB201601034"

```

```{r, message=FALSE, include=FALSE}

# **************************************************************************** #
# ***************                Library                       *************** #
# **************************************************************************** #

library(keyringr)
library(redcapAPI)
library(REDCapR)
library(tidyverse)
source("~/plasma-metabolomics/code/utils/utils.R")


```

```{r, message=FALSE,include=FALSE}

# **************************************************************************** #
# ***************              Extract Data                    *************** #
# **************************************************************************** #

# API & URL
#----------
uri <- "https://redcap.ctsi.ufl.edu/redcap/api/"
api_token=get_API_token("beach_api")
#api_token=""

# REPORT IDS
#-----------

# Study Overview
report_id<-45193L
report_name= "Diet Record: Analysis Ready"


# PULL DATA
#-----------
report_raw <-
  REDCapR::redcap_report(
    redcap_uri = uri,
    token      = api_token,
    report_id  = report_id
  )$data 


```


```{r, message=FALSE,include=FALSE}

# **************************************************************************** #
# ***************              Save Data Local                 *************** #
# **************************************************************************** #

# # Save the data in your local laptop (Github path: /data)
# save(list=c("report"),file="~/BEACH-reports/data/raw/report_39840.RData")
# 
# output_directory="~/BEACH-reports/data/raw/"
# output_file_name="report_39840.RData"

```

