---
title: 'Get RedCap Data: Diet Records Report'
author: "Dominick J. Lemas"
date: "10/11/2023"
output:
  pdf_document: default
  html_document: default
---

```{r, include=FALSE}
##-------------- 
# **************************************************************************** #
# ***************                Project Overview              *************** #
# **************************************************************************** #

# Author:            Dominick J. Lemas
# Start Date:        04/15/2023 
# Date Modify:       
# Project:           The Breastfeeding and EArly Child Health Study
# IRB:               IRB201601034
#                   
#
# R version 4.3.1 (2023-06-16 ucrt) -- "Beagle Scouts"
# Copyright (C) 2023 The R Foundation for Statistical Computing
# Platform: x86_64-w64-mingw32/x64 (64-bit) 

# **************************************************************************** #
# ***************                Description                   *************** #
# **************************************************************************** #

# PLAN: Access redcap via API and fetch/format/ready data for downstream analysis.
# Note: vpn must be active

# keyringr must be installed: https://cran.r-project.org/web/packages/keyringr/vignettes/Avoiding_plain_text_passwords_in_R_with_keyringr.html

project_name="The Breastfeeding and EArly Child Health Study"
irb_number="IRB201601034"

```

```{r, message=FALSE, include=FALSE}

# **************************************************************************** #
# ***************                Library                       *************** #
# **************************************************************************** #

library(keyringr)
library(redcapAPI)
library(REDCapR)
library(tidyverse)
# source("E:/Documents/BEACH-reports/code/utils/utils.R")
source("C:/Users/djlemas/Documents/BEACH-reports/code/utils/utils.R")



```

```{r, message=FALSE,include=FALSE}

# **************************************************************************** #
# ***************              Extract Data                    *************** #
# **************************************************************************** #

# API & URL
#----------
uri <- "https://redcap.ctsi.ufl.edu/redcap/api/"
api_token=get_API_token("beach_api")

# REPORT IDS
#-----------

# Study Overview
report_id<-45193L
report_name= "Diet Record: Analysis Ready"


# PULL DATA
#-----------
report_raw <-
  REDCapR::redcap_report(
    redcap_uri = uri,
    token      = api_token,
    report_id  = report_id
  )$data 

length(unique(report_raw$test_id)) # 83

```

```{r, message=FALSE,include=FALSE}

# complete some preliminary analysis
# diet variable: calories
full_day_kcals=report_raw %>%
  filter(meal_type=="full_day" & food_record_study_visit=="third_trimester") %>%
  filter(food_record_nutrient=="cals_kcal") %>%
  group_by(test_id) %>%
  select(test_id,food_record_day,food_record_value) %>%
  summarise(mean=mean(food_record_value)) %>%
  rename(cals_kcal_average=mean) %>%
  mutate(study_visit="third_trimester")
  length(unique(full_day_kcals$test_id)) # 45
  
# diet variable: protein
full_day_prot_g=report_raw %>%
  filter(meal_type=="full_day" & food_record_study_visit=="third_trimester") %>%
  filter(food_record_nutrient=="prot_g") %>%
  group_by(test_id) %>%
  select(test_id,food_record_day,food_record_value) %>%
  summarise(mean=mean(food_record_value)) %>%
  rename(prot_g_average=mean) %>%
  mutate(study_visit="third_trimester")

# diet variable: carbohydrates
full_day_carb_g=report_raw %>%
  filter(meal_type=="full_day" & food_record_study_visit=="third_trimester") %>%
  filter(food_record_nutrient=="carb_g") %>%
  group_by(test_id) %>%
  select(test_id,food_record_day,food_record_value) %>%
  summarise(mean=mean(food_record_value)) %>%
  rename(carb_g_average=mean) %>%
  mutate(study_visit="third_trimester")

# diet variable: fat
full_day_fat_g=report_raw %>%
  filter(meal_type=="full_day" & food_record_study_visit=="third_trimester") %>%
  filter(food_record_nutrient=="fat_g") %>%
  group_by(test_id) %>%
  select(test_id,food_record_day,food_record_value) %>%
  summarise(mean=mean(food_record_value)) %>%
  rename(fat_g_average=mean) %>%
  mutate(study_visit="third_trimester")

# diet variable: fiber
full_day_totfib_g=report_raw %>%
  filter(meal_type=="full_day" & food_record_study_visit=="third_trimester") %>%
  filter(food_record_nutrient=="totfib_g") %>%
  group_by(test_id) %>%
  select(test_id,food_record_day,food_record_value) %>%
  summarise(mean=mean(food_record_value)) %>%
  rename(totfib_g_average=mean) %>%
  mutate(study_visit="third_trimester")

# diet variable: saturated fat
full_day_satfat_g=report_raw %>%
  filter(meal_type=="full_day" & food_record_study_visit=="third_trimester") %>%
  filter(food_record_nutrient=="satfat_g") %>%
  group_by(test_id) %>%
  select(test_id,food_record_day,food_record_value) %>%
  summarise(mean=mean(food_record_value)) %>%
  rename(satfat_g_average=mean) %>%
  mutate(study_visit="third_trimester")

# diet variable: sugar
full_day_sugar_g=report_raw %>%
  filter(meal_type=="full_day" & food_record_study_visit=="third_trimester") %>%
  filter(food_record_nutrient=="sugar_g") %>%
  group_by(test_id) %>%
  select(test_id,food_record_day,food_record_value) %>%
  summarise(mean=mean(food_record_value)) %>%
  rename(sugar_g_average=mean) %>%
  mutate(study_visit="third_trimester")

# merge into eachother
data1=full_join(full_day_carb_g,full_day_fat_g) %>%
  select(test_id,study_visit,everything())

data2=full_join(data1,full_day_kcals) %>%
  select(test_id,study_visit,everything())

data3=full_join(data2,full_day_prot_g) %>%
  select(test_id,study_visit,everything())

data4=full_join(data3,full_day_satfat_g) %>%
  select(test_id,study_visit,everything())

data5=full_join(data4,full_day_sugar_g) %>%
  select(test_id,study_visit,everything())

data6=full_join(data5,full_day_totfib_g) %>%
  select(test_id,study_visit,everything())

beach_3rdtri_diet=data6

```

```{r, message=FALSE,include=FALSE}

# **************************************************************************** #
# ***************              Save Data Local                 *************** #
# **************************************************************************** #

# # Save the data in your local laptop (Github path: /data)
save(list=c("beach_3rdtri_diet"),file="~/BEACH-reports/data/raw/beach_3rdtri_diet.RData")


```
