---
title: "build_Recruitment_4"
author: "Yasmine Gillespie"
date: "2022-12-12"
output: html_document
---

```{r, include=FALSE,echo=FALSE}
##-------------- 
# **************************************************************************** #
# ***************                Project Overview              *************** #
# **************************************************************************** #

# Author:      Yasmine Gillespie
# Date:        Oct 25, 2022 
# Modify:      
# IRB:         UFHealth Early Life Exposures and Pediatric Outcomes (IRB201601899) 

# version: R version 4.2.2 (2022-10-31)
# version: Rstudio version Version 1.3.959 

# **************************************************************************** #
# ***************                Description                   *************** #
# **************************************************************************** #

# PLAN: Access redcap via API and pull/format/clean data for downstream analysis.
# Note: vpn must be active

# Next steps
#- function to call the IDs and events
#- function to batch pull EHR data by year/event 


```

```{r, message=FALSE,warning=FALSE, echo = FALSE}

# **************************************************************************** #
# ***************                Library                       *************** #
# **************************************************************************** #

knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
library(tidyverse)
library(dplyr)
library(flextable)
library(gt)
library(formattable)
library(gtsummary)
library(ggplot2)
library(ggrepel)
library(keyringr)
library(readxl)
library(redcapAPI)
library(REDCapR)
library(vtree)
library(vistime)
library(labelled)
library(plyr)
library(plotly)
library(tidyquant)
library(readr)


library(scales)
library(viridis)
library(ggthemes)
library(gridExtra)
library(lubridate)
library(data.table)

library(tidyquant)
library(ggplot2)
library(plyr)
library(plotly)
library(stringi)
library(anytime)
library(ggpattern)

# Load libraries
```

```{r, message=FALSE,include=FALSE}

# **************************************************************************** #
# ***************              Load Data                       *************** #
# ****************************************************************************#

load("~/BEACH-Reports/output/reports/recruitment/recruitment_clean.RData")
load("~/BEACH-reports/data/raw/Current_Particpant_raw.RData")

```

```{r, message=FALSE,warning=FALSE,echo=FALSE}
#make waffles

#recruitment types
Social_media= filter(recruitment_report, Recruitment == "Social Media")
Flyer = filter(recruitment_report, Recruitment == "Flyer")
Word_of_mouth = filter(recruitment_report, Recruitment == "Word-of-mouth")

#all waffle
all <- (rbind(Social_media,Word_of_mouth,Flyer))

#bmi waffle
CP_raw=CP_raw %>%
  mutate(bmi_analysis_prepregnant=recode(bmi_analysis_prepregnant,
                              "1"="Normal",
                              "2"="Overweight",
                              "3"= "Obese"
                               ))
CP_raw$BMI = coalesce(CP_raw$beach_final_bmi, CP_raw$beachphone_prepreg_bmi)
CP_raw = CP_raw %>%
   mutate(BMI = case_when((BMI >=26) ~ "OWOB", (BMI <26) ~ "NW"))

 
BMI_waffle <- cbind(recruitment_report, CP_raw$BMI)
colnames(BMI_waffle)[18] <- "bmi_group"

BMI_waffle = BMI_waffle %>% drop_na(`bmi_group`)
BMI_NW = filter(BMI_waffle, bmi_group == "NW")
BMI_OWOB = filter(BMI_waffle, bmi_group != "NW")

```
                               
#BMI-Based Waffles

###normal weight waffle
```{r, message=FALSE,include=FALSE}

BMI_NW$time = anydate(BMI_NW$timecoalesce)

NW_waffle <- count(BMI_NW$time) %>% ungroup()
names(NW_waffle) [1] <- "time"


```

```{r, message=FALSE,include=FALSE}
#normal weight waffle

NW_waffle$weekday = as.POSIXlt(NW_waffle$time)$wday #finding the day no. of the week
NW_waffle$weekdayf<-factor(NW_waffle$weekday,levels=rev(0:6),labels=rev(c("Sun","Mon","Tue","Wed","Thu","Fri","Sat")),ordered=TRUE) # converting the day no. to factor

NW_waffle$monthf<- 1

NW_waffle$monthf<-factor(month(NW_waffle$time),levels=as.character(1:12),labels=c("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"),ordered=TRUE) # finding the month

NW_waffle$yearmonth<- factor(as.yearmon(NW_waffle$time)) # finding the year and the month from the date. Eg: Nov 2018

NW_waffle$week <- as.numeric(format(NW_waffle$time,"%W")) # finding the week of the year for each date

NW_waffle<-ddply(NW_waffle,.(yearmonth),transform,monthweek=stringi::stri_datetime_fields(time)$WeekOfMonth) # normalizing the week to start at 1 for every month


n <- ggplot(NW_waffle, aes(monthweek, weekdayf, fill = freq)) + 
    geom_tile(colour = "white") + facet_grid(~NW_waffle$monthf) + scale_fill_gradient(low="red", high="green") +  xlab("Week of Month") + ylab("") + labs(fill = "# Recruited")

n
print(n)
#run individually to ensure the plot looks fine and everything worked so far

ggsave(n, filename = "c:/waffles/BMI_NW_waffle.png",height = 1.6, width = 10)
#save to computer to adjust size appropriately. adjust filename to where you want it saved

```                          

###overweight/obese waffle
```{r, message=FALSE,include=FALSE}

BMI_OWOB$time = anydate(BMI_OWOB$timecoalesce)

OWOB_waffle <- count(BMI_OWOB$time) %>% ungroup()
names(OWOB_waffle) [1] <- "time"
OWOB_waffle <- na.omit(OWOB_waffle)

```

```{r, message=FALSE,include=FALSE}
#normal weight waffle

OWOB_waffle$weekday = as.POSIXlt(OWOB_waffle$time)$wday #finding the day no. of the week
OWOB_waffle$weekdayf<-factor(OWOB_waffle$weekday,levels=rev(0:6),labels=rev(c("Sun","Mon","Tue","Wed","Thu","Fri","Sat")),ordered=TRUE) # converting the day no. to factor

OWOB_waffle$monthf<- 1

OWOB_waffle$monthf<-factor(month(OWOB_waffle$time),levels=as.character(1:12),labels=c("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"),ordered=TRUE) # finding the month

OWOB_waffle$yearmonth<- factor(as.yearmon(OWOB_waffle$time)) # finding the year and the month from the date. Eg: Nov 2018

OWOB_waffle$week <- as.numeric(format(OWOB_waffle$time,"%W")) # finding the week of the year for each date

OWOB_waffle<-ddply(OWOB_waffle,.(yearmonth),transform,monthweek=stringi::stri_datetime_fields(time)$WeekOfMonth) # normalizing the week to start at 1 for every month

o <- ggplot(OWOB_waffle, aes(monthweek, weekdayf, fill = freq)) + 
    geom_tile(colour = "white") + facet_grid(~OWOB_waffle$monthf, drop = FALSE) + scale_fill_gradient(low="red", high="green") +  xlab("Week of Month") + ylab("") + labs(fill = "# Recruited")

o
print(o)
#run individually to ensure the plot looks fine and everything worked so far

ggsave(o, filename = "c:/waffles/BMI_OWOB_waffle.png",height = 1.6, width = 10)
#save to computer to adjust size appropriately. adjust filename to where you want it saved

```

```{r,message=FALSE,include=FALSE}
#counts for each quarter

NW_months <- BMI_NW[19]
NW_months$month<-factor(month(NW_months$time),levels=as.character(1:12),labels=c("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec")) 
OWOB_months <- BMI_OWOB[19]
OWOB_months$month<-factor(month(OWOB_months$time),levels=as.character(1:12),labels=c("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec")) 

OWOB_months <- na.omit(OWOB_months)

#normal weight
sum(NW_months$month == 'Jan' | NW_months$month == 'Feb' | NW_months$month == 'Mar')
sum(NW_months$month == 'Apr' | NW_months$month == 'May' | NW_months$month == 'Jun')
sum(NW_months$month == 'Jul' | NW_months$month == 'Aug' | NW_months$month == 'Sep')
sum(NW_months$month == 'Oct' | NW_months$month == 'Nov' | NW_months$month == 'Dec')

#overweight/obese
sum(OWOB_months$month == 'Jan' | OWOB_months$month == 'Feb' | OWOB_months$month == 'Mar')
sum(OWOB_months$month == 'Apr' | OWOB_months$month == 'May' | OWOB_months$month == 'Jun')
sum(OWOB_months$month == 'Jul' | OWOB_months$month == 'Aug' | OWOB_months$month == 'Sep')
sum(OWOB_months$month == 'Oct' | OWOB_months$month == 'Nov' | OWOB_months$month == 'Dec')

```


#bar plot based on waffle plot months

```{r,message=FALSE,include=FALSE}
#make data frames
BMI_bar <- BMI_waffle[18]
BMI_bar[2] <- BMI_waffle[17]
BMI_bar$time <- anydate(BMI_waffle$timecoalesce)
BMI_bar$month<-factor(month(BMI_bar$time),levels=as.character(1:12),labels=c("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"),ordered=TRUE) # finding the month
BMI_bar = BMI_bar %>%
  select(bmi_group, month)

#creating counted data for each BMI and month
BMI_bar_counted <- count(BMI_bar)
BMI_bar_counted <- na.omit(BMI_bar_counted)
BMI_bar_counted=BMI_bar_counted %>%
  mutate(bmi_group=recode(bmi_group,
                              "NW"="Normal",
                              "OWOB"="Obese/Overweight"
                               ))


b <- ggplot(BMI_bar_counted, aes(x = month, y = freq, fill = bmi_group)) + geom_bar(stat = "identity", position = "dodge") + ylim(0,25) + geom_text(aes(label = freq), vjust = -1, position = position_dodge(width = 0.9)) + theme_light() + xlab("Month") + ylab("Participants") + guides(fill = guide_legend(title = "Obesity Status")) + theme(legend.title = element_text(size = 12), legend.text= element_text(size=12), text = element_text(size = 14))



b

ggsave(b, filename = "c:/waffles/BMI_barplot.png",height = 3, width = 10)
#save to computer to adjust size appropriately. adjust filename to where you want it saved


#adjust location of counts on barplot

```

###barplot in base R (saved in case)
```{r,message=FALSE,include=FALSE}
#make data frames

NW_months <- NW_waffle[5]
OWOB_months <- OWOB_waffle[5]
NW_bar <- table(NW_months)
OWOB_bar <- table(OWOB_months)
BMI_bar <- join(NW_bar, OWOB_bar)


#renaming
names(BMI_bar)[1] <- "month"
names(BMI_bar)[2] <- "NW_freq"
names(BMI_bar)[4] <- "OWOB_freq"
BMI_bar <- BMI_bar[ -c(3) ] #cutting out extra column

BMI_bar <- as.data.frame(t(BMI_bar))
names(BMI_bar) <- BMI_bar[1,]
BMI_bar <- BMI_bar[-1,]
#switching column and row

BMI_bar$Jan <- as.numeric(BMI_bar$Jan)
BMI_bar$Feb <- as.numeric(BMI_bar$Feb)
BMI_bar$Mar <- as.numeric(BMI_bar$Mar)
BMI_bar$Apr <- as.numeric(BMI_bar$Apr)
BMI_bar$May <- as.numeric(BMI_bar$May)
BMI_bar$Jun <- as.numeric(BMI_bar$Jun)
BMI_bar$Jul <- as.numeric(BMI_bar$Jul)
BMI_bar$Aug <- as.numeric(BMI_bar$Aug)
BMI_bar$Sep <- as.numeric(BMI_bar$Sep)
BMI_bar$Oct <- as.numeric(BMI_bar$Oct)
BMI_bar$Nov <- as.numeric(BMI_bar$Nov)
BMI_bar$Dec <- as.numeric(BMI_bar$Dec)
#changing variables in data frame to be numeric instead of character

BMI_bar1 <- as.matrix(BMI_bar)
#making matrix to plug into barplot

x11()
library(graphics)
#run to ensure graphics works

```

```{r,message=FALSE,include=FALSE}
#barplot 

barplot(BMI_bar1, beside = TRUE, ylab = "Participants", legend.text = TRUE, col = c("darkred", "blue"))

```

#Recruitment-Based Waffles (unused)
                               
###social media waffle
```{r, message=FALSE,include=FALSE}

Social_media$time=anydate(Social_media$timecoalesce)

social_waffle <- count(Social_media$time) %>% ungroup()
names(social_waffle)[1] <- "time"

```

```{r, message=FALSE,include=FALSE}
#social media waffle

social_waffle$weekday = as.POSIXlt(social_waffle$time)$wday #finding the day no. of the week
social_waffle$weekdayf<-factor(social_waffle$weekday,levels=rev(0:6),labels=rev(c("Sun","Mon","Tue","Wed","Thu","Fri","Sat")),ordered=TRUE) # converting the day no. to factor

social_waffle$monthf<- 1

social_waffle$monthf<-factor(month(social_waffle$time),levels=as.character(1:12),labels=c("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"),ordered=TRUE) # finding the month

social_waffle$yearmonth<- factor(as.yearmon(social_waffle$time)) # finding the year and the month from the date. Eg: Nov 2018
#might not need this

social_waffle$week <- as.numeric(format(social_waffle$time,"%W")) # finding the week of the year for each date

social_waffle<-ddply(social_waffle,.(yearmonth),transform,monthweek=1+week-min(week)) # normalizing the week to start at 1 for every month


p <- ggplot(social_waffle, aes(monthweek, weekdayf, fill = social_waffle$freq)) + 
    geom_tile(colour = "white") + facet_grid(~social_waffle$monthf) + scale_fill_gradient(low="red", high="green") +  xlab("Week of Month") + ylab("") + ggtitle("Time-Series Calendar Heatmap: Social media Recruitment") + labs(fill = "# Recruited")

p
print(p)
```


###flyer waffle
```{r, message=FALSE,include=FALSE}

Flyer$time=anydate(Flyer$timecoalesce)

flyer_waffle <- count(Flyer$time) %>% ungroup()
names(flyer_waffle)[1] <- "time"

```

```{r, message=FALSE,include=FALSE}
#flyer waffle

flyer_waffle$weekday = as.POSIXlt(flyer_waffle$time)$wday #finding the day no. of the week
flyer_waffle$weekdayf<-factor(flyer_waffle$weekday,levels=rev(0:6),labels=rev(c("Sun","Mon","Tue","Wed","Thu","Fri","Sat")),ordered=TRUE) # converting the day no. to factor

flyer_waffle$monthf<- 1

flyer_waffle$monthf<-factor(month(flyer_waffle$time),levels=as.character(1:12),labels=c("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"),ordered=TRUE) # finding the month

flyer_waffle$yearmonth<- factor(as.yearmon(flyer_waffle$time)) # finding the year and the month from the date. Eg: Nov 2018

flyer_waffle$week <- as.numeric(format(flyer_waffle$time,"%W")) # finding the week of the year for each date

flyer_waffle<-ddply(flyer_waffle,.(yearmonth),transform,monthweek=1+week-min(week)) # normalizing the week to start at 1 for every month

f <- ggplot(flyer_waffle, aes(monthweek, weekdayf, fill = flyer_waffle$freq)) + 
    geom_tile(colour = "white") + facet_grid(~flyer_waffle$monthf) + scale_fill_gradient(low="red", high="green") +  xlab("Week of Month") + ylab("") + ggtitle("Time-Series Calendar Heatmap: Flyer Recruitment") + labs(fill = "# Recruited")

f
print(f)
```


###word of mouth waffle
```{r, message=FALSE,include=FALSE}

Word_of_mouth$time=anydate(Word_of_mouth$timecoalesce)

word_waffle <- count(Word_of_mouth$time) %>% ungroup()
names(word_waffle)[1] <- "time"

```

```{r, message=FALSE,include=FALSE}
#word of mouth waffle

library(tidyquant)
library(ggplot2)
library(plyr)
library(plotly)

word_waffle$weekday = as.POSIXlt(word_waffle$time)$wday #finding the day no. of the week
word_waffle$weekdayf<-factor(word_waffle$weekday,levels=rev(0:6),labels=rev(c("Sun","Mon","Tue","Wed","Thu","Fri","Sat")),ordered=TRUE) # converting the day no. to factor

word_waffle$monthf<- 1

word_waffle$monthf<-factor(month(word_waffle$time),levels=as.character(1:12),labels=c("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"),ordered=TRUE) # finding the month

word_waffle$yearmonth<- factor(as.yearmon(word_waffle$time)) # finding the year and the month from the date. Eg: Nov 2018

word_waffle$week <- as.numeric(format(word_waffle$time,"%W")) # finding the week of the year for each date

word_waffle<-ddply(word_waffle,.(yearmonth),transform,monthweek=1+week-min(week)) # normalizing the week to start at 1 for every month

w <- ggplot(word_waffle, aes(monthweek, weekdayf, fill = word_waffle$freq)) + 
    geom_tile(colour = "white") + facet_grid(~word_waffle$monthf) + scale_fill_gradient(low="red", high="green") +  xlab("Week of Month") + ylab("") + ggtitle("Time-Series Calendar Heatmap: Word-of-mouth Recruitment") + labs(fill = "# Recruited")

w
print(w)
```


