---
title: "BEACH study BMI recruitment overtime"
author: "Yasmine Gillespie, Michele Himadi"
date: "2024-06-05"
output: html_document
---

```{r, include=FALSE,echo=FALSE}
##-------------- 
# **************************************************************************** #
# ***************                Project Overview              *************** #
# **************************************************************************** #

# Author:      Yasmine Gillespie, Michele Himadi
# Date:        Oct 25, 2022 
# Modify:      June 5, 2024
# IRB:         UFHealth Early Life Exposures and Pediatric Outcomes (IRB201601899) 

# version: R version 4.2.2 (2022-10-31)
# version: Rstudio version Version 1.3.959 

# **************************************************************************** #
# ***************                Description                   *************** #
# **************************************************************************** #

# PLAN: Access redcap via API and pull/format/clean data for downstream analysis.
# Note: vpn must be active

# Next steps
#- function to call the IDs and events
#- function to batch pull EHR data by year/event 


```

```{r, message=FALSE,warning=FALSE, echo = FALSE}

# **************************************************************************** #
# ***************                Library                       *************** #
# **************************************************************************** #

knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
library(tidyverse)
library(dplyr)
library(flextable)
library(gt)
library(formattable)
library(gtsummary)
library(ggplot2)
library(ggrepel)
library(keyringr)
library(readxl)
library(redcapAPI)
library(REDCapR)
library(vtree)
library(vistime)
library(labelled)
library(plyr)
library(plotly)
library(tidyquant)
library(readr)


library(scales)
library(viridis)
library(ggthemes)
library(gridExtra)
library(lubridate)
library(data.table)

library(tidyquant)
library(ggplot2)
library(plyr)
library(plotly)
library(stringi)
library(anytime)
library(ggpattern)

# Load libraries
```


```{r, message=FALSE,include=FALSE}

# **************************************************************************** #
# ***************              Load Data                       *************** #
# ****************************************************************************#

load("~/BEACH-reports/data/raw/Current_Particpant_raw.RData")

```

```{r, message=FALSE,warning=FALSE,echo=FALSE}
#make bmi categories
CP_raw$BMI = coalesce(CP_raw$beach_final_bmi, CP_raw$beachphone_prepreg_bmi, CP_raw$prescreen_prepreg_bmi)
CP_raw = CP_raw %>%
   mutate(BMI = case_when((BMI >= 30) ~ "OB",
                          (BMI >= 25 & BMI <30) ~ "OW",
                          (BMI >= 18.5 & BMI <25) ~ "NW",
                          (BMI < 18.5) ~ "UW"))
 
BMI_barplot <- cbind(recruitment_report, CP_raw$BMI)
colnames(BMI_barplot)[18] <- "bmi_group"

BMI_barplot = BMI_barplot %>% drop_na(`bmi_group`)
BMI_UW = filter(BMI_barplot, bmi_group =="UW")
BMI_NW = filter(BMI_barplot, bmi_group == "NW")
BMI_OW = filter(BMI_barplot, bmi_group == "OW")
BMI_OB = filter(BMI_barplot, bmi_group == "OB")

BMI_UW$time = anydate(BMI_UW$timecoalesce)

BMI_NW$time = anydate(BMI_NW$timecoalesce)

BMI_OW$time = anydate(BMI_OW$timecoalesce)

BMI_OB$time = anydate(BMI_OB$timecoalesce)

```


```{r,message=FALSE,include=FALSE}
#counts for each quarter

UW_months <- BMI_UW[19]
UW_months$month<-factor(month(UW_months$time),levels=as.character(1:12),labels=c("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec")) 
NW_months <- BMI_NW[19]
NW_months$month<-factor(month(NW_months$time),levels=as.character(1:12),labels=c("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec")) 
OW_months <- BMI_OW[19]
OW_months$month<-factor(month(OW_months$time),levels=as.character(1:12),labels=c("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec")) 
OB_months <- BMI_OB[19]
OB_months$month<-factor(month(OB_months$time),levels=as.character(1:12),labels=c("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec")) 


OB_months <- na.omit(OB_months)
OW_months <- na.omit(OW_months)
NW_months <- na.omit(NW_months)
UW_months <- na.omit(UW_months)

#underweight
sum(UW_months$month == 'Jan' | UW_months$month == 'Feb' | UW_months$month == 'Mar')
sum(UW_months$month == 'Apr' | UW_months$month == 'May' | UW_months$month == 'Jun')
sum(UW_months$month == 'Jul' | UW_months$month == 'Aug' | UW_months$month == 'Sep')
sum(UW_months$month %in% c('Oct', 'Nov', 'Dec'), na.rm = TRUE) #used slightly different code as nothing for UW in December

#normal weight
sum(NW_months$month == 'Jan' | NW_months$month == 'Feb' | NW_months$month == 'Mar')
sum(NW_months$month == 'Apr' | NW_months$month == 'May' | NW_months$month == 'Jun')
sum(NW_months$month == 'Jul' | NW_months$month == 'Aug' | NW_months$month == 'Sep')
sum(NW_months$month == 'Oct' | NW_months$month == 'Nov' | NW_months$month == 'Dec')

#overweight
sum(OW_months$month == 'Jan' | OW_months$month == 'Feb' | OW_months$month == 'Mar')
sum(OW_months$month == 'Apr' | OW_months$month == 'May' | OW_months$month == 'Jun')
sum(OW_months$month == 'Jul' | OW_months$month == 'Aug' | OW_months$month == 'Sep')
sum(OW_months$month == 'Oct' | OW_months$month == 'Nov' | OW_months$month == 'Dec')

#obese
sum(OB_months$month == 'Jan' | OB_months$month == 'Feb' | OB_months$month == 'Mar')
sum(OB_months$month == 'Apr' | OB_months$month == 'May' | OB_months$month == 'Jun')
sum(OB_months$month == 'Jul' | OB_months$month == 'Aug' | OB_months$month == 'Sep')
sum(OB_months$month == 'Oct' | OB_months$month == 'Nov' | OB_months$month == 'Dec')

```


#bar plot based on waffle plot months

```{r,message=FALSE,include=FALSE}
#make data frames
BMI_bar <- BMI_barplot[18]
BMI_bar[2] <- BMI_barplot[17]
BMI_bar$time <- anydate(BMI_barplot$timecoalesce)
BMI_bar$month<-factor(month(BMI_bar$time),levels=as.character(1:12),labels=c("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"),ordered=TRUE) # finding the month
BMI_bar = BMI_bar %>%
  select(bmi_group, month)

#creating counted data for each BMI and month
BMI_bar_counted <- count(BMI_bar)
BMI_bar_counted <- na.omit(BMI_bar_counted)
BMI_bar_counted=BMI_bar_counted %>%
  mutate(bmi_group=recode(bmi_group,
                              "NW"="2. Normal",
                              "OW"="3. Overweight",
                              "OB"="4. Obesity",
                              "UW" = "1. Underweight"))

b <- ggplot(BMI_bar_counted, aes(x = month, y = freq, fill = bmi_group)) + geom_bar(stat = "identity", position = "dodge") + geom_text(aes(label = freq), vjust = -1, position = position_dodge(width = 0.9)) + theme_light() + xlab("Month") + ylab("Counts") + guides(fill = guide_legend(title = "Obesity Status")) + theme(legend.title = element_text(size = 12), legend.text= element_text(size=12), text = element_text(size = 14)) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())

b

ggsave(b, filename = "BMI_barplot.png",height = 6, width = 15)
#save to computer to adjust size appropriately. adjust filename to where you want it saved

```
