---
title: "BEACH Data Inventory"
author: "Dominick Lemas"
date: "09/02/2021"
output: html_document

---

```{r, include=FALSE}
##-------------- 
# **************************************************************************** #
# ***************                Project Overview              *************** #
# **************************************************************************** #

# Author:            Dominick Lemas
# Start Date:        Feb 22, 2021 
# Date Modify:       Oct 18, 2020
# IRB:               
#                   
#
# version: R version 4.0.2 (2020-06-22)
# version: Rstudio version Version 1.3.959 

# **************************************************************************** #
# ***************                Description                   *************** #
# **************************************************************************** #

# PLAN: Access redcap via API and pull/format/clean data for downstream analysis.
# Note: vpn must be active

# keyringr: https://cran.r-project.org/web/packages/keyringr/vignettes/Avoiding_plain_text_passwords_in_R_with_keyringr.html

```


```{r, message=FALSE}

# **************************************************************************** #
# ***************                Library                       *************** #
# **************************************************************************** #

library(keyringr)
library(redcapAPI)
library(REDCapR)
library(readxl)
library(tidyverse)
source("~/BEACH-reports/code/utils.R")

```

```{r, message=FALSE}

# API & URL
#----------
url <- "https://redcap.ctsi.ufl.edu/redcap/api/"
api_token=get_API_token("beach_api")


# API and URL
uri='https://redcap.ctsi.ufl.edu/redcap/api/'
rcon <- redcapConnection(url=uri, token=api_token)

# variables of interest
desired_fields_v1=c("test_id","prescreen_prego","prescreen_height","prescreen_heightinches")

desired_records_v1=c("BLS001A","BLS002A","BLS090A")


# Access data
data = redcap_read_oneshot(
  uri,
  api_token,
  fields = desired_fields_v1,
  records = desired_records_v1,
  raw_or_label_headers = "raw")$data

data = data %>%
  as_tibble() %>%
  filter(redcap_repeat_instrument =="demographics") 



```

