---
title: "Build BEACH Table 1 Report"
author: "Dominick Lemas, Michele Himadi"
date: "3/01/2023"

---

```{r, include=FALSE}
##-------------- 
# **************************************************************************** #
# ***************                Project Overview              *************** #
# **************************************************************************** #

# Author:            Dominick J. Lemas
# Start Date:        2/07/2023 
# Date Modify:       3/1/2023
# Project:           The Breastfeeding and EArly Child Health
# IRB:               IRB201601034
#                   
#
# version: R version 4.0.2 (2020-06-22)
# version: Rstudio version Version 1.3.959 

# **************************************************************************** #
# ***************                Description                   *************** #
# **************************************************************************** #

# NOTE: This script consumes data that was generated by:
# ~/code/get/get_RedCapData_36804.Rmd
# ~/code/format/format_RedCapData_BEACHTable1.rmd

# PLAN: Complete NIH Enrollment Table.

project_name="The Breastfeeding and EArly Child Health Study"
irb_number="IRB201601034"
upstream_code="~/code/format/format_RedCapData_BEACHTable1.Rmd"
report_id<-36804L
report_name= "BEACH Table 1"
input_file="36804_BEACHTable1_clean.RData"

```


```{r, message=FALSE,include=FALSE}

# **************************************************************************** #
# ***************                Library                       *************** #
# **************************************************************************** #

library(codified)
library(tidyverse)
library(gtsummary)
library(dplyr)
library(flextable)
library(officer)
library(gt)
library(ggplot2)

load("~/BEACH-reports/data/processed/36804_BEACHTable1_clean.RData")

```

```{r, echo=FALSE}

# **************************************************************************** #
# ***************            Build Summary Table               *************** #
# **************************************************************************** #

#making table 1 that's grouped by NW, OW, OB
##changing names to reorganize columns
table1_formatted <- table1_formatted %>%
  mutate(BMI_Group = case_when(
    BMI_Group == "NW" ~ "1. Normal Weight",
    BMI_Group == "OW" ~ "2. Overweight",
    BMI_Group == "OB" ~ "3. Obese",
    TRUE ~ BMI_Group
  ))

#making table
tb_sum <- table1_formatted %>%
  tbl_summary(by = BMI_Group, type = list(Gestational_Age ~ "continuous"),
    statistic = list(
      all_continuous() ~ "{mean} ({sd})",
      all_categorical() ~ "{n} / {N} ({p}%)"
      )) %>%
  add_p() %>%
  bold_labels()

#making overall table
overall_summary <- table1_formatted %>%
  select(-BMI_Group) %>%
  tbl_summary(type = list(Gestational_Age ~ "continuous"),
    statistic = list(
      all_continuous() ~ "{mean} ({sd})",
      all_categorical() ~ "{n} / {N} ({p}%)"
      )) 

#combining overall and grouped tables
combined_table <- tbl_merge(list(overall_summary, tb_sum), tab_spanner = FALSE)

#print outputs to check
print(combined_table)
print(tb_sum)

flextable_sum <- as_flex_table(tb_sum) %>%
  set_table_properties(layout = "autofit")
flextable_combined <- as_flex_table(combined_table) %>%
  set_table_properties(layout = "autofit")
  

doc_1 <- read_docx()

doc_1 <- doc_1 %>%
  body_add_flextable(value = flextable_sum) %>%
  body_add_break() %>%
  body_add_flextable(value = flextable_combined)


print(doc_1, target = "~/GitHub/BEACH-reports/data/table1_all_v2.docx")


```

```{r, echo=FALSE}

# **************************************************************************** #
# ***************      Build Summary Table, OWOB Combined      *************** #
# **************************************************************************** #

#creating table that merges OB+OW
tbl1_OWOB <- table1_formatted %>%
  mutate(BMI_Group = case_when(
    BMI_Group == "NW" ~ "1. Normal Weight",
    BMI_Group == "2. Overweight" ~ "2. Overweight + Obese",
    BMI_Group == "3. Obese" ~ "2. Overweight + Obese",
    TRUE ~ BMI_Group
  ))


#making table
tb_OWOB <- tbl1_OWOB %>%
  tbl_summary(by = BMI_Group, type = list(Gestational_Age ~ "continuous"),
    statistic = list(
      all_continuous() ~ "{mean} ({sd})",
      all_categorical() ~ "{n} / {N} ({p}%)"
      )) %>%
  add_p() %>% #might get warning that exact p-value cannot be computed
  bold_labels()


#combining overall and grouped tables
OWOB_combined <- tbl_merge(list(overall_summary, tb_OWOB), tab_spanner = FALSE)

#print outputs to check
print(OWOB_combined)
print(tb_OWOB)

flextable_OWOB <- as_flex_table(OWOB_combined) %>%
  set_table_properties(layout = "autofit")
flextable_OWOBcombined <- as_flex_table(tb_OWOB) %>%
  set_table_properties(layout = "autofit")

doc_2 <- read_docx()

doc_2 <- doc_2 %>%
  body_add_flextable(value = flextable_OWOBcombined) %>%
  body_add_break() %>%
  body_add_flextable(value = flextable_OWOB)

print(doc_2, target = "~/GitHub/BEACH-reports/data/table1_OWOB_v1.docx")


```



###Grahping Breastfeeding Confidence, Infant Outcomes

```{r message=FALSE, include=FALSE}

# **************************************************************************** #
# ***************          Breastfeeding Confidence            *************** #
# **************************************************************************** #
#making table for breastfeeding confidence
bf_conf_graph <- table1_formatted %>% select(BMI_Group, bf_2wk = "Breastfeeding Confidence (2 Weeks)", bf_2mo = "Breastfeeding Confidence (2 Months)", bf_12mo = "Breastfeeding Confidence (12 Months)")
bf_conf_graph <- bf_conf_graph %>%
    mutate(BMI_Group = recode(BMI_Group, "NW" = 'NW', "OW" = 'OW+OB', "OB" =  'OW+OB' ))

#averaging by group
avg_bf_2wk <- mean(bf_conf_graph$bf_2wk, na.rm = TRUE)
avg_bf_2mo <- mean(bf_conf_graph$bf_2mo, na.rm = TRUE)
avg_bf_12mo <- mean(bf_conf_graph$bf_12mo, na.rm = TRUE)
avg_bf_NW_2wk <- mean(subset(bf_conf_graph, BMI_Group == "NW")$bf_2wk, na.rm = TRUE)
avg_bf_NW_2mo <- mean(subset(bf_conf_graph, BMI_Group == "NW")$bf_2mo, na.rm = TRUE)
avg_bf_NW_12mo <- mean(subset(bf_conf_graph, BMI_Group == "NW")$bf_12mo, na.rm = TRUE)
avg_bf_OWOB_2wk <- mean(subset(bf_conf_graph, BMI_Group == "OW+OB")$bf_2wk, na.rm = TRUE)
avg_bf_OWOB_2mo <- mean(subset(bf_conf_graph, BMI_Group == "OW+OB")$bf_2mo, na.rm = TRUE)
avg_bf_OWOB_12mo <- mean(subset(bf_conf_graph, BMI_Group == "OW+OB")$bf_12mo, na.rm = TRUE)


df_all <- data.frame(
  Time = factor(c("2 weeks", "2 months", "12 months"), levels = c("2 weeks", "2 months", "12 months")),
  Avg_Breastfeeding_Confidence = c(avg_bf_2wk, avg_bf_2mo, avg_bf_12mo),
  BMI_Group = "all"
)

df_NW <- data.frame(
  Time = factor(c("2 weeks", "2 months", "12 months"), levels = c("2 weeks", "2 months", "12 months")),
  Avg_Breastfeeding_Confidence = c(avg_bf_NW_2wk, avg_bf_NW_2mo, avg_bf_NW_12mo),
  BMI_Group = rep("NW", 3)
)

df_OWOB <- data.frame(
  Time = factor(c("2 weeks", "2 months", "12 months"), levels = c("2 weeks", "2 months", "12 months")),
  Avg_Breastfeeding_Confidence = c(avg_bf_OWOB_2wk, avg_bf_OWOB_2mo, avg_bf_OWOB_12mo),
  BMI_Group = rep("OWOB", 3)
)

# Combine the data frames
plot_df <- rbind(df_all, df_NW, df_OWOB)
plot_df <- plot_df %>%
    mutate(BMI_Group = recode(BMI_Group, "NW" = 'Normal Weight', "OWOB" = 'Overweight + Obese', "all" =  'All Participants' ))

# Create the plot with separate lines for each BMI group
ggplot(plot_df, aes(x = Time, y = Avg_Breastfeeding_Confidence, group = BMI_Group, color = BMI_Group)) +
  geom_line(size=1.5) +
  geom_point(size=4) +
  labs(x = "Time", y = "Breastfeeding Confidence") +
  ggtitle("Average Breastfeeding Confidence Over Time") +
  theme_bw() +
  theme(panel.grid.major.x = element_blank()) +
  scale_color_discrete(name = "BMI Group")
```

```{r message=FALSE, include=FALSE}

# **************************************************************************** #
# ***************          Infant Outcomes - Weight            *************** #
# **************************************************************************** #
#making table for breastfeeding confidence
infweight_conf_graph <- table1_formatted %>% select(BMI_Group, iw_2wk = "Infant 2wk Weight", iw_2mo = "Infant 2mo Weight", iw_12mo = "Infant 12mo Weight")
iw_conf_graph <- infweight_conf_graph %>%
    mutate(BMI_Group = recode(BMI_Group, "NW" = 'NW', "OW" = 'OW+OB', "OB" =  'OW+OB' ))

#averaging by group
avg_iw_2wk <- mean(iw_conf_graph$iw_2wk, na.rm = TRUE)
avg_iw_2mo <- mean(iw_conf_graph$iw_2mo, na.rm = TRUE)
avg_iw_12mo <- mean(iw_conf_graph$iw_12mo, na.rm = TRUE)
avg_iw_NW_2wk <- mean(subset(iw_conf_graph, BMI_Group == "NW")$iw_2wk, na.rm = TRUE)
avg_iw_NW_2mo <- mean(subset(iw_conf_graph, BMI_Group == "NW")$iw_2mo, na.rm = TRUE)
avg_iw_NW_12mo <- mean(subset(iw_conf_graph, BMI_Group == "NW")$iw_12mo, na.rm = TRUE)
avg_iw_OWOB_2wk <- mean(subset(iw_conf_graph, BMI_Group == "OW+OB")$iw_2wk, na.rm = TRUE)
avg_iw_OWOB_2mo <- mean(subset(iw_conf_graph, BMI_Group == "OW+OB")$iw_2mo, na.rm = TRUE)
avg_iw_OWOB_12mo <- mean(subset(iw_conf_graph, BMI_Group == "OW+OB")$iw_12mo, na.rm = TRUE)


df_all_iw <- data.frame(
  Time = factor(c("2 weeks", "2 months", "12 months"), levels = c("2 weeks", "2 months", "12 months")),
  Avg_Inf_Weight = c(avg_iw_2wk, avg_iw_2mo, avg_iw_12mo),
  BMI_Group = "all"
)

df_NW_iw <- data.frame(
  Time = factor(c("2 weeks", "2 months", "12 months"), levels = c("2 weeks", "2 months", "12 months")),
  Avg_Inf_Weight = c(avg_iw_NW_2wk, avg_iw_NW_2mo, avg_iw_NW_12mo),
  BMI_Group = rep("NW", 3)
)

df_OWOB_iw <- data.frame(
  Time = factor(c("2 weeks", "2 months", "12 months"), levels = c("2 weeks", "2 months", "12 months")),
  Avg_Inf_Weight = c(avg_iw_OWOB_2wk, avg_iw_OWOB_2mo, avg_iw_OWOB_12mo),
  BMI_Group = rep("OWOB", 3)
)

# Combine the data frames
plot_df <- rbind(df_all_iw, df_NW_iw, df_OWOB_iw)
plot_df <- plot_df %>%
    mutate(BMI_Group = recode(BMI_Group, "NW" = 'Normal Weight', "OWOB" = 'Overweight + Obese', "all" =  'All Participants' ))

# Create the plot with separate lines for each BMI group
ggplot(plot_df, aes(x = Time, y = Avg_Inf_Weight, group = BMI_Group, color = BMI_Group)) +
  geom_line(size=1.5) +
  geom_point(size=4) +
  labs(x = "Time", y = "Infant Weight") +
  ggtitle("Average Infant Weight Over Time") +
  theme_bw() +
  theme(panel.grid.major.x = element_blank()) +
  scale_color_discrete(name = "BMI Group")
```


```{r, message=FALSE,include=FALSE}

# **************************************************************************** #
# ***************              Samples Quantified              *************** #
# **************************************************************************** #

#create table frame with rows to describe maternal age, gestational age, breastfeeding (months)
sample1 <- data.frame(Variables = c("n and p value","Breastmilk", "Maternal Blood", "Maternal Stool", "Infant Blood", "Infant Stool", "Diet Records"))

#adding total for overall category
sample1[2,2] = sum(!is.na(sample_grouping$mompostnat_crc_milk_time))
sample1[3,2] = sum(!is.na(sample_grouping$mom3t_crc_blood_time),!is.na(sample_grouping$mompostnat_crc_blood_time))
sample1[4,2] = sum(!is.na(sample_grouping$mom3t_crc_stool_time),!is.na(sample_grouping$mompostnat_crc_stool_time))
sample1[5,2] = sum(!is.na(sample_grouping$infant_crc_blood_time))
sample1[6,2] = sum(!is.na(sample_grouping$infant_crc_stool_time))
sample1[7,2] = sum(!is.na(sample_grouping$beach_foodrecord_hardcopy))

#adding total for normal weight category
sample1[2,3] = sum(!is.na(sample_grouping_nw$mompostnat_crc_milk_time))
sample1[3,3] = sum(!is.na(sample_grouping_nw$mom3t_crc_blood_time),!is.na(sample_grouping_nw$mompostnat_crc_blood_time))
sample1[4,3] = sum(!is.na(sample_grouping_nw$mom3t_crc_stool_time),!is.na(sample_grouping_nw$mompostnat_crc_stool_time))
sample1[5,3] = sum(!is.na(sample_grouping_nw$infant_crc_blood_time))
sample1[6,3] = sum(!is.na(sample_grouping_nw$infant_crc_stool_time))
sample1[7,3] = sum(!is.na(sample_grouping_nw$beach_foodrecord_hardcopy))

#adding total for overweight category
sample1[2,4] = sum(!is.na(sample_grouping_ow$mompostnat_crc_milk_time))
sample1[3,4] = sum(!is.na(sample_grouping_ow$mom3t_crc_blood_time),!is.na(sample_grouping_ow$mompostnat_crc_blood_time))
sample1[4,4] = sum(!is.na(sample_grouping_ow$mom3t_crc_stool_time),!is.na(sample_grouping_ow$mompostnat_crc_stool_time))
sample1[5,4] = sum(!is.na(sample_grouping_ow$infant_crc_blood_time))
sample1[6,4] = sum(!is.na(sample_grouping_ow$infant_crc_stool_time))
sample1[7,4] = sum(!is.na(sample_grouping_ow$beach_foodrecord_hardcopy))

#adding total for obese category
sample1[2,5] = sum(!is.na(sample_grouping_ob$mompostnat_crc_milk_time))
sample1[3,5] = sum(!is.na(sample_grouping_ob$mom3t_crc_blood_time),!is.na(sample_grouping_ob$mompostnat_crc_blood_time))
sample1[4,5] = sum(!is.na(sample_grouping_ob$mom3t_crc_stool_time),!is.na(sample_grouping_ob$mompostnat_crc_stool_time))
sample1[5,5] = sum(!is.na(sample_grouping_ob$infant_crc_blood_time))
sample1[6,5] = sum(!is.na(sample_grouping_ob$infant_crc_stool_time))
sample1[7,5] = sum(!is.na(sample_grouping_ob$beach_foodrecord_hardcopy))

```

```{r, message=FALSE,include=FALSE}

# **************************************************************************** #
# ***************                n and p values                *************** #
# **************************************************************************** #

#remove 

#add n value and p value for each category: overall, normal weight, overweight, obese
sample1[1,2] = (paste("n =",nrow(sample_grouping),"( p =",nrow(sample_grouping)/nrow(sample_grouping)," )"))
sample1[1,3] = (paste("n =",nrow(sample_grouping_nw),"( p =", round(nrow(sample_grouping_nw)/nrow(sample_grouping), digits = 2)," )"))
sample1[1,4] = (paste("n =",nrow(sample_grouping_ow),"( p =", round(nrow(sample_grouping_ow)/nrow(sample_grouping), digits = 2)," )"))
sample1[1,5] = (paste("n =",nrow(sample_grouping_ob),"( p =", round(nrow(sample_grouping_ob)/nrow(sample_grouping), digits = 2)," )"))

#rename table columns to reflect category
colnames(sample1)[2] <- "Overall"
colnames(sample1)[3] <- "Normal Weight"
colnames(sample1)[4] <- "Overweight"
colnames(sample1)[5] <- "Obese"

```


