---
title: "Format RedCap Data: NIH Enrollment Report"
author: "Dominick Lemas"
date: "10/18/2022"
output: html_document

---

```{r, include=FALSE,echo=FALSE}
##-------------- 
# **************************************************************************** #
# ***************                Project Overview              *************** #
# **************************************************************************** #

# Author:            Dominick J. Lemas
# Start Date:        09/07/2022 
# Date Modify:       10/18/2022
# Project:           The Breastfeeding and EArly Child Health
# IRB:               IRB201601034
#                   
#
# version: R version 4.0.2 (2020-06-22)
# version: Rstudio version Version 1.3.959 

# **************************************************************************** #
# ***************                Description                   *************** #
# **************************************************************************** #

# NOTE: This script consumes data that was generated by 

# PLAN: Format data for downstream reports BMI Report

project_name="The Breastfeeding and EArly Child Health Study"
irb_number="IRB201601034"
upstream_code="~/code/get/get_RedCapData_21221.Rmd"
report_id<-21221L
report_name= "BEACH Study Overview"
input_file="report_21221.RData"

```


```{r, message=FALSE,echo=FALSE,include=FALSE}

# **************************************************************************** #
# ***************                Library                       *************** #
# **************************************************************************** #

#library(readxl)
library(tidyverse)
# source("~/BEACH-reports/code/utils/utils.R")

```

```{r, message=FALSE,include=FALSE}

# **************************************************************************** #
# ***************              Load/Trim Data                  *************** #
# **************************************************************************** #

load("~/BEACH-reports/data/raw/report_21221.RData")

enroll = report %>% select(test_id, maternal_sex_nih, mom_ethnicity_nih, 
                                maternal_race_nih___1, maternal_race_nih___2,
                                maternal_race_nih___3,
                                maternal_race_nih___4, maternal_race_nih___5, 
                                maternal_race_nih___6,
                                infant_sex_nih, infant_ethnicity_nih,  
                                infant_race_nih___1, infant_race_nih___2, infant_race_nih___3,
                                infant_race_nih___4, infant_race_nih___5, infant_race_nih___6)
  

```

```{r, message=FALSE,include=FALSE}

# create long dataset where each row is a unique mom with BMI measurements.

maternal=enroll %>%
  mutate(participant_type="maternal") %>%
  select(test_id, participant_type, maternal_sex_nih, mom_ethnicity_nih, 
         maternal_race_nih___1,
         maternal_race_nih___2, maternal_race_nih___3, maternal_race_nih___4,
         maternal_race_nih___5, maternal_race_nih___6) %>%
  rename(sex_nih=maternal_sex_nih,
         ethnicity_nih=mom_ethnicity_nih, 
         race_nih___1=maternal_race_nih___1,
         race_nih___2=maternal_race_nih___2, 
         race_nih___3=maternal_race_nih___3, 
         race_nih___4=maternal_race_nih___4,
         race_nih___5=maternal_race_nih___5, 
         race_nih___6=maternal_race_nih___6)
  
infant= enroll %>%
  mutate(participant_type="infant") %>%
  select(test_id, participant_type, infant_sex_nih, infant_ethnicity_nih, 
         infant_race_nih___1,
         infant_race_nih___2, infant_race_nih___3, infant_race_nih___4,
         infant_race_nih___5, infant_race_nih___6) %>%
  rename(sex_nih=infant_sex_nih,
         ethnicity_nih=infant_ethnicity_nih, 
         race_nih___1=infant_race_nih___1,
         race_nih___2=infant_race_nih___2, 
         race_nih___3=infant_race_nih___3, 
         race_nih___4=infant_race_nih___4,
         race_nih___5=infant_race_nih___5, 
         race_nih___6=infant_race_nih___6)

data_all = rbind(maternal,infant)

```


```{r, message=FALSE,include=FALSE}

# FORMAT DATA
#------------

data = data_all  %>% 
  gather("race", "value", race_nih___1:race_nih___6) %>%
  filter(value==1) %>%
  mutate(race=recode_factor(race,
                                     "race_nih___1" = "NativeAmerican", 
                                     "race_nih___2" = "Asian", 
                                     "race_nih___3" = "Black", 
                                     "race_nih___4" = "PacificIsland", 
                                     "race_nih___5" = "White",
                                     "race_nih___6" = "NA")) %>%
  select(-value) 

```

```{r, message=FALSE,include=FALSE}

# **************************************************************************** #
# ***************              Save Data Local                 *************** #
# **************************************************************************** #

# Save the data in your local laptop (Github path: /data)
save(list=c("data"),file="~/BEACH-reports/data/processed/21221_NIHenrollment_clean.RData")

output_directory="~/BEACH-reports/data/processed/"
output_file_name="21221_NIHenrollment_clean.RData"

```
