---
title: "Format Infant Outcomes"
author: "Dominick J. Lemas, Michele Himadi"
date: "8/16/2023"

---

```{r, include=FALSE}
##-------------- 
# **************************************************************************** #
# ***************                Project Overview              *************** #
# **************************************************************************** #

# Author:            Dominick J. Lemas
# Start Date:        2/07/2022 
# Date Modify:       3/01/2023
# Project:           The Breastfeeding and EArly Child Health Study
# IRB:               IRB201601034
#                   
#
# version: R version 4.0.2 (2020-06-22)
# version: Rstudio version Version 1.3.959 

# **************************************************************************** #
# ***************                Description                   *************** #
# **************************************************************************** #

# NOTE: This script consumes data that was generated by 

# PLAN: Format data for downstream reports NIH Enrollment Report

project_name="The Breastfeeding and EArly Child Health Study"
irb_number="IRB201601034"
upstream_code="~/code/get/get_RedCapData_36804.Rmd"
report_id<-21221L
report_name= "BEACH Study Overview"
input_file="report_21221.RData"

```


```{r, message=FALSE,echo=FALSE,include=FALSE}

# **************************************************************************** #
# ***************                Library                       *************** #
# **************************************************************************** #

#library(readxl)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(eeptools)
library(zoo)
# source("~/BEACH-reports/code/utils/utils.R")

```

```{r, message=FALSE,include=FALSE}

# **************************************************************************** #
# ***************              Load/Trim Data                  *************** #
# **************************************************************************** #

load("~/BEACH-reports/data/raw/report_21221.RData")

```

```{r, message=FALSE,include=FALSE}
outcomes = report %>%
  select(test_id, overview_gest_age, overview_birthweight)

mean(outcomes$overview_gest_age, na.rm = TRUE)
mean(outcomes$overview_birthweight, na.rm = TRUE)
#39.12, 3.44

range(outcomes$overview_gest_age, na.rm=TRUE)
range(outcomes$overview_birthweight, na.rm = TRUE)
#35-43, 2.44-4.86

sum(is.na(outcomes$overview_gest_age))
#missing = 23
sum(is.na(outcomes$overview_birthweight))
#missing = 28

write.csv(outcomes, file = "~/infant_outcomes")
```
