---
title: "Format Problems During Pregnancy"
author: "Dominick J. Lemas, Michele Himadi"
date: "2/14/2023"

---

```{r, include=FALSE}
##-------------- 
# **************************************************************************** #
# ***************                Project Overview              *************** #
# **************************************************************************** #

# Author:            Dominick J. Lemas
# Start Date:        2/07/2022 
# Date Modify:       3/01/2023
# Project:           The Breastfeeding and EArly Child Health Study
# IRB:               IRB201601034
#                   
#
# version: R version 4.0.2 (2020-06-22)
# version: Rstudio version Version 1.3.959 

# **************************************************************************** #
# ***************                Description                   *************** #
# **************************************************************************** #

# NOTE: This script consumes data that was generated by 

# PLAN: Format data for downstream reports NIH Enrollment Report

project_name="The Breastfeeding and EArly Child Health Study"
irb_number="IRB201601034"
upstream_code="~/code/get/get_RedCapData_36804.Rmd"
report_id<-37206L
report_name= "Problems During Pregnancy"
input_file="report_36804.RData"

```


```{r, message=FALSE,echo=FALSE,include=FALSE}

# **************************************************************************** #
# ***************                Library                       *************** #
# **************************************************************************** #

#library(readxl)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(eeptools)
library(zoo)
library(janitor)
# source("~/BEACH-reports/code/utils/utils.R")

```

```{r, message=FALSE,include=FALSE}

# **************************************************************************** #
# ***************              Load/Trim Data                  *************** #
# **************************************************************************** #
load("~/BEACH-reports/data/raw/report_37206.RData")
#https://statsandr.com/blog/anova-in-r/ 

df_table = df %>% select(-overview_gest_age, -beach_final_bmi, -test_id, -mom2wk_infant_nicu)
df_table[df_table == "no"] <- "0"
df_table[df_table == "yes"] <- "1"

df_bmi_hospstay = df_table %>% select(maternal_study_groups, mom2wk_infant_hosp_stay)
df_tb_bmi_hospstay <- table(df_bmi_hospstay)
barplot(df_tb_bmi_hospstay, legend.text = TRUE, beside = TRUE)

df_nicu = df %>% select(mom2wk_infant_nicu)
df_nicu[df_nicu == "no"] <- "0"
df_nicu[df_nicu == "yes"] <- "1"
df_nicu = df_nicu %>% mutate_if(is.character, as.numeric)
df_nicu <- cbind(df_nicu, maternal_study_groups = df$maternal_study_groups)

#
nicu_aov <- aov(mom2wk_infant_nicu ~ maternal_study_groups, data = df_nicu)
summary(nicu_aov)

#
df_table_problems = df_table %>% select(-maternal_study_groups, -mom2wk_infant_hosp_stay) %>% 
  mutate_if(is.character, as.numeric)


df_ob_hosp <- tabyl(df_table, maternal_study_groups, mom2wk_infant_hosp_stay)


df_problems_ob <- cbind(df_table_problems, maternal_study_groups = df$maternal_study_groups)

#df_problems_sums <- df_problems_ob %>% mutate(sum_of_rows = rowSums(.[-22]))

df_table_all = df_problems_ob %>%
  group_by(maternal_study_groups) %>% 
  summarise(across(everything(), ~ sum(.x, na.rm = TRUE)))

df_aov = df_problems_sums %>% select(maternal_study_groups, sum_of_rows)
#df_aov <- as.matrix(df_aov)
#oneway.test(problems ~ maternal_study_groups,
            #data = df_aov,
            #var.equal = TRUE)

#
#problems_aov <- aov(sum_of_rows ~ maternal_study_groups, data = df_aov)
#summary(problems_aov)
```

```{r, echo=FALSE, message=FALSE}
#
problems_aov <- aov(sum_of_rows ~ maternal_study_groups, data = df_aov)
summary(problems_aov)

#
nicu_aov <- aov(mom2wk_infant_nicu ~ maternal_study_groups, data = df_nicu)
summary(nicu_aov)

#
barplot(df_tb_bmi_hospstay, legend.text = TRUE, beside = TRUE)

```


```

```{r, message=FALSE, include=FALSE}

# **************************************************************************** #
# ***************              Save Data Local                 *************** #
# **************************************************************************** #

# Save the data in your local laptop (Github path: /data)
save(list=c("table1_formatted", "sample_grouping"),file="~/BEACH-reports/data/processed/36804_BEACHTable1_clean.RData")

output_directory="~/BEACH-reports/data/processed/"
output_file_name="BEACHTable1.RData"

```

