---
title: "Format RedCap Data: NIH Enrollment Report"
author: "Dominick Lemas"
date: "10/18/2022"
output: html_document

---

```{r, include=FALSE,echo=FALSE}
##-------------- 
# **************************************************************************** #
# ***************                Project Overview              *************** #
# **************************************************************************** #

# Author:            Dominick J. Lemas
# Start Date:        09/07/2022 
# Date Modify:       10/18/2022
# Project:           The Breastfeeding and EArly Child Health
# IRB:               IRB201601034
#                   
#
# version: R version 4.0.2 (2020-06-22)
# version: Rstudio version Version 1.3.959 

# **************************************************************************** #
# ***************                Description                   *************** #
# **************************************************************************** #

# NOTE: This script consumes data that was generated by 

# PLAN: Format data for downstream reports BMI Report

project_name="The Breastfeeding and EArly Child Health Study"
irb_number="IRB201601034"
upstream_code="~/code/get/get_RedCapData_21221.Rmd"
report_id<-36954L
report_name= "BEACH Study Overview"
input_file="report_21221.RData"

```


```{r, message=FALSE,echo=FALSE,include=FALSE}

# **************************************************************************** #
# ***************                Library                       *************** #
# **************************************************************************** #

#library(readxl)
library(tidyverse)
# source("~/BEACH-reports/code/utils/utils.R")
#install devtools https://www.r-project.org/nosvn/pandoc/devtools.html
#after download, type ".libPath()" to find what folder to add the installed devtools folder to (should be something like Program Files/R/R-4.4.2/library)
library(devtools)
build_github_devtools()
install.packages("devtools.zip", repos = NULL)
library(devtools)
install_github("dreidpath/SGA-LGA")

```

```{r, message=FALSE,include=FALSE}

# **************************************************************************** #
# ***************              Load/Trim Data                  *************** #
# **************************************************************************** #

load("~/BEACH-reports/data/raw/report_36954.RData")

bmi = report %>% select(test_id, beach_final_bmi)
  

```

```{r, message=FALSE,include=FALSE}

# **************************************************************************** #
# ***************              Save Data Local                 *************** #
# **************************************************************************** #

# Save the data in your local laptop (Github path: /data)
save(list=c("bmi"),file="~/BEACH-reports/data/processed/21221_MaternalBMI_clean.RData")

output_directory="~/BEACH-reports/data/processed/"
output_file_name="21221_MaternalBMI_clean.RData"

```
