---
title: "Format BEACH Table 1"
author: "Dominick J. Lemas, Michele Himadi"
date: "2/14/2023"

---

```{r, include=FALSE}
##-------------- 
# **************************************************************************** #
# ***************                Project Overview              *************** #
# **************************************************************************** #

# Author:            Dominick J. Lemas
# Start Date:        2/07/2022 
# Date Modify:       3/01/2023
# Project:           The Breastfeeding and EArly Child Health Study
# IRB:               IRB201601034
#                   
#
# version: R version 4.0.2 (2020-06-22)
# version: Rstudio version Version 1.3.959 

# **************************************************************************** #
# ***************                Description                   *************** #
# **************************************************************************** #

# NOTE: This script consumes data that was generated by 

# PLAN: Format data for downstream reports NIH Enrollment Report

project_name="The Breastfeeding and EArly Child Health Study"
irb_number="IRB201601034"
upstream_code="~/code/get/get_RedCapData_36804.Rmd"
report_id<-36804L
report_name= "BEACH Table 1"
input_file="report_36804.RData"

```


```{r, message=FALSE,echo=FALSE,include=FALSE}

# **************************************************************************** #
# ***************                Library                       *************** #
# **************************************************************************** #

#library(readxl)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(eeptools)
library(zoo)
# source("~/BEACH-reports/code/utils/utils.R")

```

```{r, message=FALSE,include=FALSE}

# **************************************************************************** #
# ***************              Load/Trim Data                  *************** #
# **************************************************************************** #

#load("~/BEACH-reports/data/raw/report_39840.RData")

#create one row for each participant with their respective data
participants <- report %>%
  group_by(test_id, metabolite_name) %>%
  fill(everything(), .direction = "down") %>%
  fill(everything(), .direction = "up") %>%
  slice(1)

metadata_v4 <- participants %>% select(test_id, crc_specimen_barcode_v2, crc_specimen_number_v2, beach_final_bmi, maternal_study_groups, overview_birthweight, overview_inf_twowk_weight, overview_inf_twomo_weight, overview_inf_twemo_weight, overview_bf_check, overview_mom_bf, overview_gest_age, part_dob, mom2wk_delivery_date, infant_delivery___1, infant_delivery___2, infant_delivery___3, infant_delivery___4, infant_delivery___5, infant_delivery___6, beach_last_visit_nih)

#can take out if using metabolite name
metadata_v4 <- metadata_v4[-1]
metadata_v4_merged <- metadata_v4 %>%
  group_by(test_id) %>%
  fill(everything(), .direction = "down") %>%
  fill(everything(), .direction = "up") %>%
  slice(1)

#renaming/recoding
metadata_v4_merged$maternal_study_groups[metadata_v4_merged$maternal_study_groups == "1"] <- "NW"
metadata_v4_merged$maternal_study_groups[metadata_v4_merged$maternal_study_groups == "2"] <- "OW"
metadata_v4_merged$maternal_study_groups[metadata_v4_merged$maternal_study_groups == "3"] <- "OB"
metadata_v4_merged$beach_last_visit_nih[metadata_v4_merged$beach_last_visit_nih == "1"] <- "3rd Trimester"
metadata_v4_merged$beach_last_visit_nih[metadata_v4_merged$beach_last_visit_nih == "2"] <- "2 Week"
metadata_v4_merged$beach_last_visit_nih[metadata_v4_merged$beach_last_visit_nih == "3"] <- "2 Month"
metadata_v4_merged$beach_last_visit_nih[metadata_v4_merged$beach_last_visit_nih == "4"] <- "6 Month"
metadata_v4_merged$beach_last_visit_nih[metadata_v4_merged$beach_last_visit_nih == "5"] <- "12 Month"

#changing breastfeeding so if mom did not stop breastfeeding, shows as 12 months
metadata_v4_merged$overview_bf_check[metadata_v4_merged$overview_bf_check == "2"] <- "12"
metadata_v4_merged$overview_bf_check[metadata_v4_merged$overview_bf_check == "3"] <- NA
metadata_v4_merged$overview_bf_check <- as.numeric(metadata_v4_merged$overview_bf_check)
metadata_v4_merged$overview_mom_bf <- as.numeric(metadata_v4_merged$overview_mom_bf)

metadata_v4_merged$breastfeeding_months <- coalesce(metadata_v4_merged$overview_mom_bf, metadata_v4_merged$overview_bf_check)

#delivery location
metadata_v4_merged$infant_delivery___1[metadata_v4_merged$infant_delivery___1 == "1"] <- "UF Health"
metadata_v4_merged$infant_delivery___2[metadata_v4_merged$infant_delivery___2 == "1"] <- "North Florida"
metadata_v4_merged$infant_delivery___3[metadata_v4_merged$infant_delivery___3 == "1"] <- "Alliance Pediatrics"
metadata_v4_merged$infant_delivery___4[metadata_v4_merged$infant_delivery___4 == "1"] <- "Other"
metadata_v4_merged$infant_delivery___5[metadata_v4_merged$infant_delivery___5 == "1"] <- "Other"
metadata_v4_merged$infant_delivery___6[metadata_v4_merged$infant_delivery___6 == "1"] <- "Unknown"
metadata_v4_merged$infant_delivery___1[metadata_v4_merged$infant_delivery___1 == "0"] <- NA
metadata_v4_merged$infant_delivery___2[metadata_v4_merged$infant_delivery___2 == "0"] <- NA
metadata_v4_merged$infant_delivery___3[metadata_v4_merged$infant_delivery___3 == "0"] <- NA
metadata_v4_merged$infant_delivery___4[metadata_v4_merged$infant_delivery___4 == "0"] <- NA
metadata_v4_merged$infant_delivery___5[metadata_v4_merged$infant_delivery___5 == "0"] <- NA
metadata_v4_merged$infant_delivery___6[metadata_v4_merged$infant_delivery___6 == "0"] <- NA

metadata_v4_merged$delivery_location <- coalesce(metadata_v4_merged$infant_delivery___1, metadata_v4_merged$infant_delivery___2, metadata_v4_merged$infant_delivery___3, metadata_v4_merged$infant_delivery___4, metadata_v4_merged$infant_delivery___5, metadata_v4_merged$infant_delivery___6)

```

```{r, message=FALSE, include=FALSE}
# **************************************************************************** #
# ***************               Delivery Location               *************** #
# **************************************************************************** #


```

```{r, message=FALSE, include=FALSE}
# **************************************************************************** #
# ***************                Calculating Age               *************** #
# **************************************************************************** #

#ensure ggplot2 and eeptools are downloaded


for (i in 1:nrow(metadata_v4_merged)) {
  if(is.na(metadata_v4_merged[[i,13]]) == FALSE & is.na(metadata_v4_merged[[i,14]]) == FALSE){
    metadata_v4_merged[i,24] <- (as.numeric(difftime(metadata_v4_merged[[i,14]], metadata_v4_merged[[i,13]], units = "days"))) / 365
  }
}
colnames(metadata_v4_merged)[24] <- "Maternal_Age"
metadata_v4_merged$Maternal_Age <- round(metadata_v4_merged$Maternal_Age, digits = 2)


metadata_v4_cleaned <- metadata_v4_merged %>% select(test_id, crc_specimen_barcode_v2, crc_specimen_number_v2, beach_final_bmi, maternal_study_groups, overview_birthweight, overview_inf_twowk_weight, overview_inf_twomo_weight, overview_inf_twemo_weight, delivery_location, breastfeeding_months, Maternal_Age)
```

```{r, message=FALSE, include=FALSE}
# **************************************************************************** #
# ***************            Sorting By BMI_Group              *************** #
# **************************************************************************** #

table1_formatted <- age_calc_final[order(age_calc_final$BMI),]

```

```{r, message=FALSE, include=FALSE}

# **************************************************************************** #
# ***************              Save Data Local                 *************** #
# **************************************************************************** #

# Save the data in your local laptop (Github path: /data)
save(list=c("table1_formatted", "sample_grouping"),file="~/BEACH-reports/data/processed/36804_BEACHTable1_clean.RData")

output_directory="~/BEACH-reports/data/processed/"
output_file_name="BEACHTable1.RData"

```

